// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:1a3f088d84642298df267db9a16b0262710e818534a2edbd3c044fe5f29683b4

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-lint-licenses engine (fields currently unused - validation only)
type Spec struct {
	// Patterns to exclude from scanning (optional, currently unused)
	ExcludePatterns []string `json:"excludePatterns,omitempty"`
	// Root directory to scan for Go files (optional, currently unused)
	RootDir string `json:"rootDir,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "excludePatterns":
		case "rootDir":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are excludePatterns, rootDir", key)
		}
	}
	// Parse excludePatterns
	if v, ok := m["excludePatterns"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ExcludePatterns = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ExcludePatterns = append(s.ExcludePatterns, str)
				} else {
					return nil, fmt.Errorf("field excludePatterns[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ExcludePatterns = arr
		} else {
			return nil, fmt.Errorf("field excludePatterns: expected []string, got %T", v)
		}
	}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.ExcludePatterns) > 0 {
		m["excludePatterns"] = s.ExcludePatterns
	}
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
