// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:5a8da545e75255029c5420994d66a67c895310a24268c52acaa250ebb5c29ec0

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
)

// Name is the engine name.
const Name = "go-gen-mocks-dep-detector"

// Version information (set via ldflags during build).
// Default is "dev" so GetEffectiveVersion() reads actual version from Go's debug.ReadBuildInfo()
// when running via "go run module@version".
var (
	Version        = "dev"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the go-gen-mocks-dep-detector engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServerBase(Name, Version)
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	// Register detectDependencies tool
	registerDetectDependenciesTool(server)

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// registerDetectDependenciesTool registers the detectDependencies MCP tool.
// This function must be implemented by the engine author in a separate file.
// The implementation should call mcpserver.RegisterTool with the appropriate handler.
var registerDetectDependenciesTool func(server *mcpserver.Server)
