// Code generated by forge-dev. DO NOT EDIT.
// Source: forge-dev.yaml + spec.openapi.yaml
// SourceChecksum: sha256:0ed360607fb313d7da590d3a6ac8aed3c0f487d75a01e5ad7cced96d76d2b2f5

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/enginecli"
	"github.com/alexandremahdhaoui/forge/pkg/engineframework"
)

// Name is the engine name.
const Name = "testenv-lcr"

// Version information (set via ldflags during build).
// Default is "dev" so GetEffectiveVersion() reads actual version from Go's debug.ReadBuildInfo()
// when running via "go run module@version".
var (
	Version        = "dev"
	CommitSHA      = "unknown"
	BuildTimestamp = "unknown"
)

// main is the entry point for the testenv-lcr engine.
func main() {
	enginecli.Bootstrap(enginecli.Config{
		Name:           Name,
		Version:        Version,
		CommitSHA:      CommitSHA,
		BuildTimestamp: BuildTimestamp,
		RunCLI:         nil, // Generated engines are MCP-only
		RunMCP:         runMCPServer,
		DocsConfig:     docsConfig,
	})
}

// runMCPServer creates and runs the MCP server.
func runMCPServer() error {
	server, err := SetupMCPServer(Name, Version, Create, Delete)
	if err != nil {
		return fmt.Errorf("setting up MCP server: %w", err)
	}

	// Register docs MCP tools (docs-list, docs-get)
	if err := RegisterDocsMCPTools(server); err != nil {
		return fmt.Errorf("registering docs MCP tools: %w", err)
	}

	if err := server.Run(context.Background()); err != nil {
		return fmt.Errorf("running MCP server: %w", err)
	}

	return nil
}

// Create is the create function that must be implemented by the engine author.
// Signature: func(ctx context.Context, input engineframework.CreateInput, spec *Spec) (*engineframework.TestEnvArtifact, error)
// This is a placeholder - the actual implementation should be in a separate file.
var _ = func() CreateFunc {
	return func(_ context.Context, _ engineframework.CreateInput, _ *Spec) (*engineframework.TestEnvArtifact, error) {
		panic("Create function not implemented - create a separate file with the implementation")
	}
}

// Delete is the delete function that must be implemented by the engine author.
// Signature: func(ctx context.Context, input engineframework.DeleteInput, spec *Spec) error
// This is a placeholder - the actual implementation should be in a separate file.
var _ = func() DeleteFunc {
	return func(_ context.Context, _ engineframework.DeleteInput, _ *Spec) error {
		panic("Delete function not implemented - create a separate file with the implementation")
	}
}
