// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:8a1b2f8383dcc3b4a0df32294a176294dce2d2726a6aa6c6070f9077849ccade

package main

import (
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateValueFrom validates a ValueFrom and returns validation results.
// It checks required fields and validates enum values.
func ValidateValueFrom(s *ValueFrom) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateBasicAuth validates a BasicAuth and returns validation results.
// It checks required fields and validates enum values.
func ValidateBasicAuth(s *BasicAuth) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required reference field: password
	// Validate nested reference: password
	{
		nested := s.Password
		nestedResult := ValidateValueFrom(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.password." + e.Field,
					Message: e.Message,
				})
			}
		}
	}
	// Validate required reference field: username
	// Validate nested reference: username
	{
		nested := s.Username
		nestedResult := ValidateValueFrom(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.username." + e.Field,
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateImageSource validates a ImageSource and returns validation results.
// It checks required fields and validates enum values.
func ValidateImageSource(s *ImageSource) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate nested reference: basicAuth
	{
		nested := s.BasicAuth
		nestedResult := ValidateBasicAuth(&nested)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   "spec.basicAuth." + e.Field,
					Message: e.Message,
				})
			}
		}
	}
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate array of references: images
	for i, item := range s.Images {
		nestedResult := ValidateImageSource(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.images[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
