// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:34c2458170703ae5a5ab7c31d27d44ad20d3aa3043f7d3f88957be61ed1d3b0d

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for testenv-lcr. Controls local container registry behavior.
type Spec struct {
	// Whether the local container registry is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Name of the image pull secret to create
	ImagePullSecretName string `json:"imagePullSecretName,omitempty"`
	// List of namespaces to create image pull secrets in
	ImagePullSecretNamespaces []string `json:"imagePullSecretNamespaces,omitempty"`
	// Kubernetes namespace for the registry deployment
	Namespace string `json:"namespace,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "enabled":
		case "imagePullSecretName":
		case "imagePullSecretNamespaces":
		case "namespace":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are enabled, imagePullSecretName, imagePullSecretNamespaces, namespace", key)
		}
	}
	// Parse enabled
	if v, ok := m["enabled"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Enabled = val
		} else {
			return nil, fmt.Errorf("field enabled: expected bool, got %T", v)
		}
	}
	// Parse imagePullSecretName
	if v, ok := m["imagePullSecretName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ImagePullSecretName = val
		} else {
			return nil, fmt.Errorf("field imagePullSecretName: expected string, got %T", v)
		}
	}
	// Parse imagePullSecretNamespaces
	if v, ok := m["imagePullSecretNamespaces"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ImagePullSecretNamespaces = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ImagePullSecretNamespaces = append(s.ImagePullSecretNamespaces, str)
				} else {
					return nil, fmt.Errorf("field imagePullSecretNamespaces[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ImagePullSecretNamespaces = arr
		} else {
			return nil, fmt.Errorf("field imagePullSecretNamespaces: expected []string, got %T", v)
		}
	}
	// Parse namespace
	if v, ok := m["namespace"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Namespace = val
		} else {
			return nil, fmt.Errorf("field namespace: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Enabled {
		m["enabled"] = s.Enabled
	}
	if s.ImagePullSecretName != "" {
		m["imagePullSecretName"] = s.ImagePullSecretName
	}
	if len(s.ImagePullSecretNamespaces) > 0 {
		m["imagePullSecretNamespaces"] = s.ImagePullSecretNamespaces
	}
	if s.Namespace != "" {
		m["namespace"] = s.Namespace
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
