// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:8a1b2f8383dcc3b4a0df32294a176294dce2d2726a6aa6c6070f9077849ccade

package main

import (
	"fmt"
)

// ValueFrom represents the ValueFrom configuration.
// Where a credential value comes from, exactly one of the two.
type ValueFrom struct {
	// Read the value from this environment variable
	EnvName string `json:"envName,omitempty"`
	// The value itself
	Literal string `json:"literal,omitempty"`
}

// BasicAuth represents the BasicAuth configuration.
// Credentials for pulling a private image.
type BasicAuth struct {
	Password ValueFrom `json:"password"`
	Username ValueFrom `json:"username"`
}

// ImageSource represents the ImageSource configuration.
// One image to push into the registry.
type ImageSource struct {
	BasicAuth BasicAuth `json:"basicAuth,omitempty"`
	// Image reference, local://name:tag or registry/path:tag
	Name string `json:"name"`
}

// Spec represents the Spec configuration.
// Configuration for testenv-lcr. Controls local container registry behavior.
type Spec struct {
	// Whether the local container registry is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Name of the image pull secret to create
	ImagePullSecretName string `json:"imagePullSecretName,omitempty"`
	// List of namespaces to create image pull secrets in
	ImagePullSecretNamespaces []string `json:"imagePullSecretNamespaces,omitempty"`
	// Images to push into the registry once it is up. A local:// name is an image the build stage produced on this machine; anything else is pulled from its registry, with basicAuth when it is private.
	Images []ImageSource `json:"images,omitempty"`
	// Kubernetes namespace for the registry deployment
	Namespace string `json:"namespace,omitempty"`
}

// ValueFromFromMap creates a ValueFrom from a map[string]interface{}.
func ValueFromFromMap(m map[string]interface{}) (*ValueFrom, error) {
	if m == nil {
		return &ValueFrom{}, nil
	}

	s := &ValueFrom{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "envName":
		case "literal":
		default:
			return nil, fmt.Errorf("field %s: not a key of ValueFrom; the keys are envName, literal", key)
		}
	}
	// Parse envName
	if v, ok := m["envName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.EnvName = val
		} else {
			return nil, fmt.Errorf("field envName: expected string, got %T", v)
		}
	}
	// Parse literal
	if v, ok := m["literal"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Literal = val
		} else {
			return nil, fmt.Errorf("field literal: expected string, got %T", v)
		}
	}
	return s, nil
}

// BasicAuthFromMap creates a BasicAuth from a map[string]interface{}.
func BasicAuthFromMap(m map[string]interface{}) (*BasicAuth, error) {
	if m == nil {
		return &BasicAuth{}, nil
	}

	s := &BasicAuth{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "password":
		case "username":
		default:
			return nil, fmt.Errorf("field %s: not a key of BasicAuth; the keys are password, username", key)
		}
	}
	// Parse password
	if v, ok := m["password"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := ValueFromFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field password: %w", err)
			}
			if ref != nil {
				s.Password = *ref
			}
		} else {
			return nil, fmt.Errorf("field password: expected object, got %T", v)
		}
	}
	// Parse username
	if v, ok := m["username"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := ValueFromFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field username: %w", err)
			}
			if ref != nil {
				s.Username = *ref
			}
		} else {
			return nil, fmt.Errorf("field username: expected object, got %T", v)
		}
	}
	return s, nil
}

// ImageSourceFromMap creates a ImageSource from a map[string]interface{}.
func ImageSourceFromMap(m map[string]interface{}) (*ImageSource, error) {
	if m == nil {
		return &ImageSource{}, nil
	}

	s := &ImageSource{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "basicAuth":
		case "name":
		default:
			return nil, fmt.Errorf("field %s: not a key of ImageSource; the keys are basicAuth, name", key)
		}
	}
	// Parse basicAuth
	if v, ok := m["basicAuth"]; ok && v != nil {
		if obj, ok := v.(map[string]interface{}); ok {
			ref, err := BasicAuthFromMap(obj)
			if err != nil {
				return nil, fmt.Errorf("field basicAuth: %w", err)
			}
			if ref != nil {
				s.BasicAuth = *ref
			}
		} else {
			return nil, fmt.Errorf("field basicAuth: expected object, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "enabled":
		case "imagePullSecretName":
		case "imagePullSecretNamespaces":
		case "images":
		case "namespace":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are enabled, imagePullSecretName, imagePullSecretNamespaces, images, namespace", key)
		}
	}
	// Parse enabled
	if v, ok := m["enabled"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Enabled = val
		} else {
			return nil, fmt.Errorf("field enabled: expected bool, got %T", v)
		}
	}
	// Parse imagePullSecretName
	if v, ok := m["imagePullSecretName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ImagePullSecretName = val
		} else {
			return nil, fmt.Errorf("field imagePullSecretName: expected string, got %T", v)
		}
	}
	// Parse imagePullSecretNamespaces
	if v, ok := m["imagePullSecretNamespaces"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ImagePullSecretNamespaces = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ImagePullSecretNamespaces = append(s.ImagePullSecretNamespaces, str)
				} else {
					return nil, fmt.Errorf("field imagePullSecretNamespaces[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ImagePullSecretNamespaces = arr
		} else {
			return nil, fmt.Errorf("field imagePullSecretNamespaces: expected []string, got %T", v)
		}
	}
	// Parse images
	if v, ok := m["images"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Images = make([]ImageSource, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ImageSourceFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field images[%d]: %w", i, err)
					}
					if ref != nil {
						s.Images = append(s.Images, *ref)
					}
				} else {
					return nil, fmt.Errorf("field images[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field images: expected []object, got %T", v)
		}
	}
	// Parse namespace
	if v, ok := m["namespace"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Namespace = val
		} else {
			return nil, fmt.Errorf("field namespace: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a ValueFrom to a map[string]interface{}.
func (s *ValueFrom) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.EnvName != "" {
		m["envName"] = s.EnvName
	}
	if s.Literal != "" {
		m["literal"] = s.Literal
	}
	return m
}

// ToMap converts a BasicAuth to a map[string]interface{}.
func (s *BasicAuth) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type ValueFrom
	if refMap := s.Password.ToMap(); len(refMap) > 0 {
		m["password"] = refMap
	}
	// Reference type ValueFrom
	if refMap := s.Username.ToMap(); len(refMap) > 0 {
		m["username"] = refMap
	}
	return m
}

// ToMap converts a ImageSource to a map[string]interface{}.
func (s *ImageSource) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	// Reference type BasicAuth
	if refMap := s.BasicAuth.ToMap(); len(refMap) > 0 {
		m["basicAuth"] = refMap
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Enabled {
		m["enabled"] = s.Enabled
	}
	if s.ImagePullSecretName != "" {
		m["imagePullSecretName"] = s.ImagePullSecretName
	}
	if len(s.ImagePullSecretNamespaces) > 0 {
		m["imagePullSecretNamespaces"] = s.ImagePullSecretNamespaces
	}
	if len(s.Images) > 0 {
		arr := make([]interface{}, 0, len(s.Images))
		for _, item := range s.Images {
			arr = append(arr, item.ToMap())
		}
		m["images"] = arr
	}
	if s.Namespace != "" {
		m["namespace"] = s.Namespace
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
