name: tooling

# -- build defines the artifacts to build and the artifact store location.
build:
  # -- artifactStorePath is the path to the artifact store yaml file.
  artifactStorePath: .ignore.artifact-store.yaml
  # -- specs defines the list of artifacts to build.
  specs:
    # Binaries
    - binary:
        name: kindenv
        source: ./cmd/kindenv
    - binary:
        name: local-container-registry
        source: ./cmd/local-container-registry
    - binary:
        name: test-go
        source: ./cmd/test-go
    # Containers
    - container:
        name: for-testing-purposes
        file: ./containers/for-testing-purposes/Containerfile

kindenv:
  kubeconfigPath: .ignore.kindenv.kubeconfig.yaml

# -- localContainerRegistry will create if enabled a container registry in the kindenv using the kubeconfig which path
#    is defined by {.kindenv.kubeconfigPath}.
localContainerRegistry:
  # -- autoPushImages defines whether to automatically push images from artifact store on setup.
  autoPushImages: true
  # -- enabled defines whether the local container registry must be created or not.
  enabled: true
  # -- creadentialPath defines the output file containing the container registry credentials.
  credentialPath: .ignore.local-container-registry.yaml
  # -- path to CA certificate.
  caCrtPath: .ignore.ca.crt
  # -- namespace where the local container registry will be deployed.
  namespace: local-container-registry

oapiCodegenHelper: {}

