// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:56acefe78587ef28990bc9a4820fb2bc98279167fcfb2e2d5890567da4cfeeb6

package main

import (
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: holder
	if s.Holder == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.holder",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
