// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:56acefe78587ef28990bc9a4820fb2bc98279167fcfb2e2d5890567da4cfeeb6

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for the go-license-header engine
type Spec struct {
	// Additional directory names to skip, beyond the built-in defaults (target, vendor, .git, build, tmp, .tmp, node_modules)
	//
	ExcludeDirs []string `json:"excludeDirs,omitempty"`
	// Copyright holder name to insert into new headers
	Holder string `json:"holder"`
	// Root directory to scan for *.go files (defaults to src or current directory)
	RootDir string `json:"rootDir,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "excludeDirs":
		case "holder":
		case "rootDir":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are excludeDirs, holder, rootDir", key)
		}
	}
	// Parse excludeDirs
	if v, ok := m["excludeDirs"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ExcludeDirs = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ExcludeDirs = append(s.ExcludeDirs, str)
				} else {
					return nil, fmt.Errorf("field excludeDirs[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ExcludeDirs = arr
		} else {
			return nil, fmt.Errorf("field excludeDirs: expected []string, got %T", v)
		}
	}
	// Parse holder
	if v, ok := m["holder"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Holder = val
		} else {
			return nil, fmt.Errorf("field holder: expected string, got %T", v)
		}
	}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.ExcludeDirs) > 0 {
		m["excludeDirs"] = s.ExcludeDirs
	}
	if s.Holder != "" {
		m["holder"] = s.Holder
	}
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
