// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:8ac46915f3b6881e6272a4b40fe8eff9128d4e37f37a7590075ba3b2edac36c1

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for the container-build-simple engine
type Spec struct {
	// The base image. Use "scratch" for none.
	// A static binary runs on scratch, so the base exists for whatever else runs alongside it. For a CI job container that is a shell and glibc, which is why the default is a debian and not an alpine: musl breaks JavaScript actions in edge cases, and every "uses:" step in a workflow is a JavaScript action.
	//
	Base string `json:"base,omitempty"`
	// Where the files land inside the image, and the front of PATH.
	BinDir string `json:"binDir,omitempty"`
	// Environment variables to set in the image config.
	Env map[string]string `json:"env,omitempty"`
	// What goes into the layer, relative to the repository. Two shapes, told apart by what is on disk:
	// A directory holding a forge.yaml contributes that repository's built binaries by RECORD: every artifact of type binary its artifact store carries for one of the platforms this entry declares, each landing on its own platform under the artifact's name. Nothing is parsed out of a file name.
	// Anything else is a glob of files that land on every platform, because a script or a certificate is the same on all of them. A glob that matches nothing fails the build, because an image that silently ships empty fails on the runner that tries to use it, days later and far from the cause.
	// The platforms assembled are the build entry's own platforms: declaration, and each becomes one manifest in the index.
	//
	From []string `json:"from"`
	// Labels to set in the image config.
	Labels map[string]string `json:"labels,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "base":
		case "binDir":
		case "env":
		case "from":
		case "labels":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are base, binDir, env, from, labels", key)
		}
	}
	// Parse base
	if v, ok := m["base"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Base = val
		} else {
			return nil, fmt.Errorf("field base: expected string, got %T", v)
		}
	}
	// Parse binDir
	if v, ok := m["binDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.BinDir = val
		} else {
			return nil, fmt.Errorf("field binDir: expected string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	// Parse from
	if v, ok := m["from"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.From = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.From = append(s.From, str)
				} else {
					return nil, fmt.Errorf("field from[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.From = arr
		} else {
			return nil, fmt.Errorf("field from: expected []string, got %T", v)
		}
	}
	// Parse labels
	if v, ok := m["labels"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Labels = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Labels[key] = str
				} else {
					return nil, fmt.Errorf("field labels[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Labels = mapVal
		} else {
			return nil, fmt.Errorf("field labels: expected map[string]string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Base != "" {
		m["base"] = s.Base
	}
	if s.BinDir != "" {
		m["binDir"] = s.BinDir
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	if len(s.From) > 0 {
		m["from"] = s.From
	}
	if len(s.Labels) > 0 {
		m["labels"] = s.Labels
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
