// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:0b07b9d2493e0db866b214e71bda92e75979f6629efd8ab7eb8a29720e828579

package main

import (
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
)

// ValidateValueReference validates a ValueReference and returns validation results.
// It checks required fields and validates enum values.
func ValidateValueReference(s *ValueReference) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: kind
	if s.Kind == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.kind",
			Message: "required field is missing",
		})
	}
	// Validate enum field: kind
	if s.Kind != "" {
		validValues := []string{"ConfigMap", "Secret"}
		valid := false
		for _, v := range validValues {
			if s.Kind == v {
				valid = true
				break
			}
		}
		if !valid {
			errors = append(errors, mcptypes.ValidationError{
				Field:   "spec.kind",
				Message: "must be one of: ConfigMap, Secret",
			})
		}
	}
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateChartSpec validates a ChartSpec and returns validation results.
// It checks required fields and validates enum values.
func ValidateChartSpec(s *ChartSpec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate required field: name
	if s.Name == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.name",
			Message: "required field is missing",
		})
	}
	// Validate enum field: ociProvider
	if s.OciProvider != "" {
		validValues := []string{"cosign", "notation"}
		valid := false
		for _, v := range validValues {
			if s.OciProvider == v {
				valid = true
				break
			}
		}
		if !valid {
			errors = append(errors, mcptypes.ValidationError{
				Field:   "spec.ociProvider",
				Message: "must be one of: cosign, notation",
			})
		}
	}
	// Validate required field: sourceType
	if s.SourceType == "" {
		errors = append(errors, mcptypes.ValidationError{
			Field:   "spec.sourceType",
			Message: "required field is missing",
		})
	}
	// Validate enum field: sourceType
	if s.SourceType != "" {
		validValues := []string{"git", "helm-repo", "local", "oci", "s3"}
		valid := false
		for _, v := range validValues {
			if s.SourceType == v {
				valid = true
				break
			}
		}
		if !valid {
			errors = append(errors, mcptypes.ValidationError{
				Field:   "spec.sourceType",
				Message: "must be one of: git, helm-repo, local, oci, s3",
			})
		}
	}
	// Validate array of references: valueReferences
	for i, item := range s.ValueReferences {
		nestedResult := ValidateValueReference(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.valueReferences[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// ValidateSpec validates a Spec and returns validation results.
// It checks required fields and validates enum values.
func ValidateSpec(s *Spec) *mcptypes.ConfigValidateOutput {
	if s == nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: true,
		}
	}

	var errors []mcptypes.ValidationError
	// Validate array of references: charts
	for i, item := range s.Charts {
		nestedResult := ValidateChartSpec(&item)
		if !nestedResult.Valid {
			for _, e := range nestedResult.Errors {
				errors = append(errors, mcptypes.ValidationError{
					Field:   fmt.Sprintf("spec.charts[%d].%s", i, e.Field),
					Message: e.Message,
				})
			}
		}
	}

	if len(errors) > 0 {
		return &mcptypes.ConfigValidateOutput{
			Valid:  false,
			Errors: errors,
		}
	}

	return &mcptypes.ConfigValidateOutput{
		Valid: true,
	}
}

// Validate validates a Spec and returns validation results.
// This is the main entry point for validation.
func Validate(s *Spec) *mcptypes.ConfigValidateOutput {
	return ValidateSpec(s)
}

// ValidateMap validates a map[string]interface{} by first parsing it to a Spec.
// This is a convenience function for validating spec data from forge.yaml.
func ValidateMap(m map[string]interface{}) *mcptypes.ConfigValidateOutput {
	s, err := FromMap(m)
	if err != nil {
		return &mcptypes.ConfigValidateOutput{
			Valid: false,
			Errors: []mcptypes.ValidationError{
				{
					Field:   "spec",
					Message: err.Error(),
				},
			},
		}
	}

	return Validate(s)
}
