// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:0b07b9d2493e0db866b214e71bda92e75979f6629efd8ab7eb8a29720e828579

package main

import (
	"fmt"
)

// ValueReference represents the ValueReference configuration.
// Values taken from a ConfigMap or a Secret that is already in the cluster.
type ValueReference struct {
	// Resource the values are read from
	Kind string `json:"kind"`
	// Name of the resource in the namespace of the release
	Name string `json:"name"`
	// Skip the reference instead of failing when the resource is missing
	Optional bool `json:"optional,omitempty"`
	// Dot separated path the values are merged into. The root when this is empty
	TargetPath string `json:"targetPath,omitempty"`
	// Key of the resource to read. Every key is merged when this is empty
	ValuesKey string `json:"valuesKey,omitempty"`
}

// ChartSpec represents the ChartSpec configuration.
// One Helm release, where its chart comes from and how it is installed.
type ChartSpec struct {
	// Secret in the release namespace holding the credentials for the source. A dockerconfigjson for oci, an accessKeyID and a secretAccessKey for s3
	AuthSecretName string `json:"authSecretName,omitempty"`
	// Name of the chart in the repository index, for a helm-repo source
	ChartName string `json:"chartName,omitempty"`
	// Path to the chart inside the source. A directory for git, the object key of the tarball for s3
	ChartPath string `json:"chartPath,omitempty"`
	// Create the namespace when it does not exist
	CreateNamespace bool `json:"createNamespace,omitempty"`
	// Skip the hooks of the chart
	DisableHooks bool `json:"disableHooks,omitempty"`
	// Return as soon as the manifests are applied instead of waiting for readiness
	DisableWait bool `json:"disableWait,omitempty"`
	// Let helm recreate a resource it cannot patch
	ForceUpgrade bool `json:"forceUpgrade,omitempty"`
	// Branch to check out, lowest precedence of the four git references
	GitBranch string `json:"gitBranch,omitempty"`
	// Commit sha to check out, highest precedence of the four git references
	GitCommit string `json:"gitCommit,omitempty"`
	// Semver range matched against the tags of the repository
	GitSemVer string `json:"gitSemVer,omitempty"`
	// Tag to check out
	GitTag string `json:"gitTag,omitempty"`
	// Identifier for this release inside the test environment
	Name string `json:"name"`
	// Namespace the release is installed into
	Namespace string `json:"namespace,omitempty"`
	// Media type of the layer holding the chart, for an oci source
	OciLayerMediaType string `json:"ociLayerMediaType,omitempty"`
	// Signature verification provider for an oci source
	OciProvider string `json:"ociProvider,omitempty"`
	// Directory holding the chart, relative to the project root, for a local source
	Path string `json:"path,omitempty"`
	// Helm release name in the cluster. Defaults to name
	ReleaseName string `json:"releaseName,omitempty"`
	// Bucket holding the chart tarball, for an s3 source
	S3BucketName string `json:"s3BucketName,omitempty"`
	// Region of the bucket. Defaults to us-east-1
	S3BucketRegion string `json:"s3BucketRegion,omitempty"`
	// Where the chart comes from
	SourceType string `json:"sourceType"`
	// Run helm test after the release is installed
	TestEnable bool `json:"testEnable,omitempty"`
	// Time helm waits for one operation. Defaults to 5m
	Timeout string `json:"timeout,omitempty"`
	// Locator for the source. The repository index for helm-repo, the clone url for git, the oci reference for oci, the endpoint for s3
	Url string `json:"url,omitempty"`
	// Values read from resources already in the cluster
	ValueReferences []ValueReference `json:"valueReferences,omitempty"`
	// Helm values written inline, highest precedence of the three value sources
	Values map[string]interface{} `json:"values,omitempty"`
	// Value files inside the chart, lowest precedence of the three value sources
	ValuesFiles []string `json:"valuesFiles,omitempty"`
	// Version constraint passed to helm
	Version string `json:"version,omitempty"`
}

// Spec represents the Spec configuration.
// Configuration for testenv-helm-install. Every release it installs is declared here.
type Spec struct {
	// The Helm releases to install, in order, into the cluster the entry before this one stood up.
	Charts []ChartSpec `json:"charts,omitempty"`
}

// ValueReferenceFromMap creates a ValueReference from a map[string]interface{}.
func ValueReferenceFromMap(m map[string]interface{}) (*ValueReference, error) {
	if m == nil {
		return &ValueReference{}, nil
	}

	s := &ValueReference{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "kind":
		case "name":
		case "optional":
		case "targetPath":
		case "valuesKey":
		default:
			return nil, fmt.Errorf("field %s: not a key of ValueReference; the keys are kind, name, optional, targetPath, valuesKey", key)
		}
	}
	// Parse kind
	if v, ok := m["kind"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Kind = val
		} else {
			return nil, fmt.Errorf("field kind: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse optional
	if v, ok := m["optional"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Optional = val
		} else {
			return nil, fmt.Errorf("field optional: expected bool, got %T", v)
		}
	}
	// Parse targetPath
	if v, ok := m["targetPath"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.TargetPath = val
		} else {
			return nil, fmt.Errorf("field targetPath: expected string, got %T", v)
		}
	}
	// Parse valuesKey
	if v, ok := m["valuesKey"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ValuesKey = val
		} else {
			return nil, fmt.Errorf("field valuesKey: expected string, got %T", v)
		}
	}
	return s, nil
}

// ChartSpecFromMap creates a ChartSpec from a map[string]interface{}.
func ChartSpecFromMap(m map[string]interface{}) (*ChartSpec, error) {
	if m == nil {
		return &ChartSpec{}, nil
	}

	s := &ChartSpec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "authSecretName":
		case "chartName":
		case "chartPath":
		case "createNamespace":
		case "disableHooks":
		case "disableWait":
		case "forceUpgrade":
		case "gitBranch":
		case "gitCommit":
		case "gitSemVer":
		case "gitTag":
		case "name":
		case "namespace":
		case "ociLayerMediaType":
		case "ociProvider":
		case "path":
		case "releaseName":
		case "s3BucketName":
		case "s3BucketRegion":
		case "sourceType":
		case "testEnable":
		case "timeout":
		case "url":
		case "valueReferences":
		case "values":
		case "valuesFiles":
		case "version":
		default:
			return nil, fmt.Errorf("field %s: not a key of ChartSpec; the keys are authSecretName, chartName, chartPath, createNamespace, disableHooks, disableWait, forceUpgrade, gitBranch, gitCommit, gitSemVer, gitTag, name, namespace, ociLayerMediaType, ociProvider, path, releaseName, s3BucketName, s3BucketRegion, sourceType, testEnable, timeout, url, valueReferences, values, valuesFiles, version", key)
		}
	}
	// Parse authSecretName
	if v, ok := m["authSecretName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.AuthSecretName = val
		} else {
			return nil, fmt.Errorf("field authSecretName: expected string, got %T", v)
		}
	}
	// Parse chartName
	if v, ok := m["chartName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ChartName = val
		} else {
			return nil, fmt.Errorf("field chartName: expected string, got %T", v)
		}
	}
	// Parse chartPath
	if v, ok := m["chartPath"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ChartPath = val
		} else {
			return nil, fmt.Errorf("field chartPath: expected string, got %T", v)
		}
	}
	// Parse createNamespace
	if v, ok := m["createNamespace"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.CreateNamespace = val
		} else {
			return nil, fmt.Errorf("field createNamespace: expected bool, got %T", v)
		}
	}
	// Parse disableHooks
	if v, ok := m["disableHooks"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.DisableHooks = val
		} else {
			return nil, fmt.Errorf("field disableHooks: expected bool, got %T", v)
		}
	}
	// Parse disableWait
	if v, ok := m["disableWait"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.DisableWait = val
		} else {
			return nil, fmt.Errorf("field disableWait: expected bool, got %T", v)
		}
	}
	// Parse forceUpgrade
	if v, ok := m["forceUpgrade"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.ForceUpgrade = val
		} else {
			return nil, fmt.Errorf("field forceUpgrade: expected bool, got %T", v)
		}
	}
	// Parse gitBranch
	if v, ok := m["gitBranch"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.GitBranch = val
		} else {
			return nil, fmt.Errorf("field gitBranch: expected string, got %T", v)
		}
	}
	// Parse gitCommit
	if v, ok := m["gitCommit"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.GitCommit = val
		} else {
			return nil, fmt.Errorf("field gitCommit: expected string, got %T", v)
		}
	}
	// Parse gitSemVer
	if v, ok := m["gitSemVer"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.GitSemVer = val
		} else {
			return nil, fmt.Errorf("field gitSemVer: expected string, got %T", v)
		}
	}
	// Parse gitTag
	if v, ok := m["gitTag"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.GitTag = val
		} else {
			return nil, fmt.Errorf("field gitTag: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse namespace
	if v, ok := m["namespace"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Namespace = val
		} else {
			return nil, fmt.Errorf("field namespace: expected string, got %T", v)
		}
	}
	// Parse ociLayerMediaType
	if v, ok := m["ociLayerMediaType"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.OciLayerMediaType = val
		} else {
			return nil, fmt.Errorf("field ociLayerMediaType: expected string, got %T", v)
		}
	}
	// Parse ociProvider
	if v, ok := m["ociProvider"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.OciProvider = val
		} else {
			return nil, fmt.Errorf("field ociProvider: expected string, got %T", v)
		}
	}
	// Parse path
	if v, ok := m["path"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Path = val
		} else {
			return nil, fmt.Errorf("field path: expected string, got %T", v)
		}
	}
	// Parse releaseName
	if v, ok := m["releaseName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.ReleaseName = val
		} else {
			return nil, fmt.Errorf("field releaseName: expected string, got %T", v)
		}
	}
	// Parse s3BucketName
	if v, ok := m["s3BucketName"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.S3BucketName = val
		} else {
			return nil, fmt.Errorf("field s3BucketName: expected string, got %T", v)
		}
	}
	// Parse s3BucketRegion
	if v, ok := m["s3BucketRegion"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.S3BucketRegion = val
		} else {
			return nil, fmt.Errorf("field s3BucketRegion: expected string, got %T", v)
		}
	}
	// Parse sourceType
	if v, ok := m["sourceType"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.SourceType = val
		} else {
			return nil, fmt.Errorf("field sourceType: expected string, got %T", v)
		}
	}
	// Parse testEnable
	if v, ok := m["testEnable"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.TestEnable = val
		} else {
			return nil, fmt.Errorf("field testEnable: expected bool, got %T", v)
		}
	}
	// Parse timeout
	if v, ok := m["timeout"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Timeout = val
		} else {
			return nil, fmt.Errorf("field timeout: expected string, got %T", v)
		}
	}
	// Parse url
	if v, ok := m["url"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Url = val
		} else {
			return nil, fmt.Errorf("field url: expected string, got %T", v)
		}
	}
	// Parse valueReferences
	if v, ok := m["valueReferences"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ValueReferences = make([]ValueReference, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ValueReferenceFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field valueReferences[%d]: %w", i, err)
					}
					if ref != nil {
						s.ValueReferences = append(s.ValueReferences, *ref)
					}
				} else {
					return nil, fmt.Errorf("field valueReferences[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field valueReferences: expected []object, got %T", v)
		}
	}
	// Parse values
	if v, ok := m["values"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Values = make(map[string]interface{}, len(mapVal))
			for key, val := range mapVal {
				s.Values[key] = val.(interface{})
			}
		} else {
			return nil, fmt.Errorf("field values: expected map, got %T", v)
		}
	}
	// Parse valuesFiles
	if v, ok := m["valuesFiles"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ValuesFiles = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ValuesFiles = append(s.ValuesFiles, str)
				} else {
					return nil, fmt.Errorf("field valuesFiles[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ValuesFiles = arr
		} else {
			return nil, fmt.Errorf("field valuesFiles: expected []string, got %T", v)
		}
	}
	// Parse version
	if v, ok := m["version"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Version = val
		} else {
			return nil, fmt.Errorf("field version: expected string, got %T", v)
		}
	}
	return s, nil
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "charts":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are charts", key)
		}
	}
	// Parse charts
	if v, ok := m["charts"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Charts = make([]ChartSpec, 0, len(arr))
			for i, item := range arr {
				if obj, ok := item.(map[string]interface{}); ok {
					ref, err := ChartSpecFromMap(obj)
					if err != nil {
						return nil, fmt.Errorf("field charts[%d]: %w", i, err)
					}
					if ref != nil {
						s.Charts = append(s.Charts, *ref)
					}
				} else {
					return nil, fmt.Errorf("field charts[%d]: expected object, got %T", i, item)
				}
			}
		} else {
			return nil, fmt.Errorf("field charts: expected []object, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a ValueReference to a map[string]interface{}.
func (s *ValueReference) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Kind != "" {
		m["kind"] = s.Kind
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Optional {
		m["optional"] = s.Optional
	}
	if s.TargetPath != "" {
		m["targetPath"] = s.TargetPath
	}
	if s.ValuesKey != "" {
		m["valuesKey"] = s.ValuesKey
	}
	return m
}

// ToMap converts a ChartSpec to a map[string]interface{}.
func (s *ChartSpec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.AuthSecretName != "" {
		m["authSecretName"] = s.AuthSecretName
	}
	if s.ChartName != "" {
		m["chartName"] = s.ChartName
	}
	if s.ChartPath != "" {
		m["chartPath"] = s.ChartPath
	}
	if s.CreateNamespace {
		m["createNamespace"] = s.CreateNamespace
	}
	if s.DisableHooks {
		m["disableHooks"] = s.DisableHooks
	}
	if s.DisableWait {
		m["disableWait"] = s.DisableWait
	}
	if s.ForceUpgrade {
		m["forceUpgrade"] = s.ForceUpgrade
	}
	if s.GitBranch != "" {
		m["gitBranch"] = s.GitBranch
	}
	if s.GitCommit != "" {
		m["gitCommit"] = s.GitCommit
	}
	if s.GitSemVer != "" {
		m["gitSemVer"] = s.GitSemVer
	}
	if s.GitTag != "" {
		m["gitTag"] = s.GitTag
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Namespace != "" {
		m["namespace"] = s.Namespace
	}
	if s.OciLayerMediaType != "" {
		m["ociLayerMediaType"] = s.OciLayerMediaType
	}
	if s.OciProvider != "" {
		m["ociProvider"] = s.OciProvider
	}
	if s.Path != "" {
		m["path"] = s.Path
	}
	if s.ReleaseName != "" {
		m["releaseName"] = s.ReleaseName
	}
	if s.S3BucketName != "" {
		m["s3BucketName"] = s.S3BucketName
	}
	if s.S3BucketRegion != "" {
		m["s3BucketRegion"] = s.S3BucketRegion
	}
	if s.SourceType != "" {
		m["sourceType"] = s.SourceType
	}
	if s.TestEnable {
		m["testEnable"] = s.TestEnable
	}
	if s.Timeout != "" {
		m["timeout"] = s.Timeout
	}
	if s.Url != "" {
		m["url"] = s.Url
	}
	if len(s.ValueReferences) > 0 {
		arr := make([]interface{}, 0, len(s.ValueReferences))
		for _, item := range s.ValueReferences {
			arr = append(arr, item.ToMap())
		}
		m["valueReferences"] = arr
	}
	if len(s.Values) > 0 {
		m["values"] = s.Values
	}
	if len(s.ValuesFiles) > 0 {
		m["valuesFiles"] = s.ValuesFiles
	}
	if s.Version != "" {
		m["version"] = s.Version
	}
	return m
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Charts) > 0 {
		arr := make([]interface{}, 0, len(s.Charts))
		for _, item := range s.Charts {
			arr = append(arr, item.ToMap())
		}
		m["charts"] = arr
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
