// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:923bd78a20f1fb040013beaade5e80c214a04e15005fd88840976d84a2d3c14d

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-lint-tags. All fields are optional.
type Spec struct {
	// List of expected build tags to check for (default is unit, integration, e2e)
	ExpectedTags []string `json:"expectedTags,omitempty"`
	// Root directory to scan for test files (default is current directory)
	RootDir string `json:"rootDir,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "expectedTags":
		case "rootDir":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are expectedTags, rootDir", key)
		}
	}
	// Parse expectedTags
	if v, ok := m["expectedTags"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.ExpectedTags = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.ExpectedTags = append(s.ExpectedTags, str)
				} else {
					return nil, fmt.Errorf("field expectedTags[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.ExpectedTags = arr
		} else {
			return nil, fmt.Errorf("field expectedTags: expected []string, got %T", v)
		}
	}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.ExpectedTags) > 0 {
		m["expectedTags"] = s.ExpectedTags
	}
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
