// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:b821bdbcf8f0f8b5d9c1ee4ffb82a4257b6ac50658fd04cfad1c1967e991eb3f

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-lint engine
type Spec struct {
	// Additional arguments to pass to golangci-lint (optional)
	Args []string `json:"args,omitempty"`
	// Path to golangci-lint config file (optional)
	Config string `json:"config,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "args":
		case "config":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are args, config", key)
		}
	}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse config
	if v, ok := m["config"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Config = val
		} else {
			return nil, fmt.Errorf("field config: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if s.Config != "" {
		m["config"] = s.Config
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
