// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:a18235387c5299bf4e812ec090e616517f095144100e5b5687f6eb52a0e3e489

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for parallel-builder engine
type Spec struct {
	// List of sub-builder configurations to run in parallel. Each item must be an object with 'engine' (required), 'name' (optional), and 'spec' (optional) fields.
	Builders []interface{} `json:"builders"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "builders":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are builders", key)
		}
	}
	// Parse builders
	if v, ok := m["builders"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Builders = make([]interface{}, 0, len(arr))
			for _, item := range arr {
				s.Builders = append(s.Builders, item.(interface{}))
			}
		} else {
			return nil, fmt.Errorf("field builders: expected array, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Builders) > 0 {
		m["builders"] = s.Builders
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
