// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockeventualconfig

import (
	"github.com/alexandremahdhaoui/forge/pkg/eventualconfig"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventualConfig creates a new instance of MockEventualConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventualConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventualConfig {
	mock := &MockEventualConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventualConfig is an autogenerated mock type for the EventualConfig type
type MockEventualConfig struct {
	mock.Mock
}

type MockEventualConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventualConfig) EXPECT() *MockEventualConfig_Expecter {
	return &MockEventualConfig_Expecter{mock: &_m.Mock}
}

// GetValue provides a mock function for the type MockEventualConfig
func (_mock *MockEventualConfig) GetValue(key eventualconfig.Key) (<-chan any, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 <-chan any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(eventualconfig.Key) (<-chan any, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(eventualconfig.Key) <-chan any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(eventualconfig.Key) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventualConfig_GetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValue'
type MockEventualConfig_GetValue_Call struct {
	*mock.Call
}

// GetValue is a helper method to define mock.On call
//   - key eventualconfig.Key
func (_e *MockEventualConfig_Expecter) GetValue(key any) *MockEventualConfig_GetValue_Call {
	return &MockEventualConfig_GetValue_Call{Call: _e.mock.On("GetValue", key)}
}

func (_c *MockEventualConfig_GetValue_Call) Run(run func(key eventualconfig.Key)) *MockEventualConfig_GetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 eventualconfig.Key
		if args[0] != nil {
			arg0 = args[0].(eventualconfig.Key)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventualConfig_GetValue_Call) Return(vCh <-chan any, err error) *MockEventualConfig_GetValue_Call {
	_c.Call.Return(vCh, err)
	return _c
}

func (_c *MockEventualConfig_GetValue_Call) RunAndReturn(run func(key eventualconfig.Key) (<-chan any, error)) *MockEventualConfig_GetValue_Call {
	_c.Call.Return(run)
	return _c
}

// SetValue provides a mock function for the type MockEventualConfig
func (_mock *MockEventualConfig) SetValue(key eventualconfig.Key, value any) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(eventualconfig.Key, any) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventualConfig_SetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetValue'
type MockEventualConfig_SetValue_Call struct {
	*mock.Call
}

// SetValue is a helper method to define mock.On call
//   - key eventualconfig.Key
//   - value any
func (_e *MockEventualConfig_Expecter) SetValue(key any, value any) *MockEventualConfig_SetValue_Call {
	return &MockEventualConfig_SetValue_Call{Call: _e.mock.On("SetValue", key, value)}
}

func (_c *MockEventualConfig_SetValue_Call) Run(run func(key eventualconfig.Key, value any)) *MockEventualConfig_SetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 eventualconfig.Key
		if args[0] != nil {
			arg0 = args[0].(eventualconfig.Key)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventualConfig_SetValue_Call) Return(err error) *MockEventualConfig_SetValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventualConfig_SetValue_Call) RunAndReturn(run func(key eventualconfig.Key, value any) error) *MockEventualConfig_SetValue_Call {
	_c.Call.Return(run)
	return _c
}
