// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:0f6c7423835997be98586057d3377f81f6c003e1a158946ba3bf815b69950605

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for testenv-kind. All fields are optional.
type Spec struct {
	// Path to kind config file for cluster customization
	Config string `json:"config,omitempty"`
	// Kind node image to use (e.g., kindest/node:v1.27.0)
	Image string `json:"image,omitempty"`
	// Custom name suffix for the kind cluster (default uses test ID)
	Name string `json:"name,omitempty"`
	// Whether to retain the cluster on failure for debugging
	Retain bool `json:"retain,omitempty"`
	// Timeout for waiting for cluster to be ready (e.g., 5m)
	WaitTimeout string `json:"waitTimeout,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "config":
		case "image":
		case "name":
		case "retain":
		case "waitTimeout":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are config, image, name, retain, waitTimeout", key)
		}
	}
	// Parse config
	if v, ok := m["config"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Config = val
		} else {
			return nil, fmt.Errorf("field config: expected string, got %T", v)
		}
	}
	// Parse image
	if v, ok := m["image"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Image = val
		} else {
			return nil, fmt.Errorf("field image: expected string, got %T", v)
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Name = val
		} else {
			return nil, fmt.Errorf("field name: expected string, got %T", v)
		}
	}
	// Parse retain
	if v, ok := m["retain"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.Retain = val
		} else {
			return nil, fmt.Errorf("field retain: expected bool, got %T", v)
		}
	}
	// Parse waitTimeout
	if v, ok := m["waitTimeout"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.WaitTimeout = val
		} else {
			return nil, fmt.Errorf("field waitTimeout: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Config != "" {
		m["config"] = s.Config
	}
	if s.Image != "" {
		m["image"] = s.Image
	}
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Retain {
		m["retain"] = s.Retain
	}
	if s.WaitTimeout != "" {
		m["waitTimeout"] = s.WaitTimeout
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
