// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:1524d02bf50e07507eaa61577533ee01c731ffd0dac50fb0dedab6c9ee49c0cb

package main

import (
	"context"
	"fmt"

	"github.com/alexandremahdhaoui/forge/pkg/engineframework"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
	"github.com/alexandremahdhaoui/forge/pkg/mcpserver"
	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/alexandremahdhaoui/forge/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// BuildFunc is the signature for the build operation with typed Spec.
// This is the function that engine authors implement. It answers one
// artifact per platform in input.Platforms, or one artifact tied to no
// platform; the framework has already refused any platform outside
// Capabilities, so the function sees only what it declared it can build.
type BuildFunc func(ctx context.Context, input mcptypes.BuildInput, s *Spec) ([]forge.Artifact, error)

// Capabilities is what forge-dev.yaml declares this engine can do. The
// build tool refuses a platform outside it, or a frozen input it never
// declared, before the engine's own code runs; config-validate refuses a
// platform before anything builds and answers the declaration so the
// caller learns what it may send.
var Capabilities = engineframework.Capabilities{Platforms: []string{"any"}, Frozen: true}

// SetupMCPServer creates and configures the MCP server with all required tools.
// It registers build, buildBatch, and config-validate tools.
func SetupMCPServer(name string, version string, buildFn BuildFunc) (*mcpserver.Server, error) {
	server := mcpserver.New(name, version)

	config := engineframework.BuilderConfig{
		Name:         name,
		Version:      version,
		BuildFunc:    wrapBuildFunc(buildFn),
		Capabilities: Capabilities,
	}

	if err := engineframework.RegisterBuilderTools(server, config); err != nil {
		return nil, fmt.Errorf("failed to register builder tools: %w", err)
	}

	// Register config-validate tool
	mcpserver.RegisterTool(server, &mcp.Tool{
		Name:        "config-validate",
		Description: fmt.Sprintf("Validate %s engine-specific spec configuration from forge.yaml build[].spec entries.", name),
	}, handleConfigValidate)

	return server, nil
}

// wrapBuildFunc wraps a typed BuildFunc into an engineframework.BuilderFunc.
// It handles parsing and validation of the Spec from the input.
func wrapBuildFunc(fn BuildFunc) engineframework.BuilderFunc {
	return func(ctx context.Context, input mcptypes.BuildInput) ([]forge.Artifact, error) {
		// Parse Spec from input
		spec, err := FromMap(input.Spec)
		if err != nil {
			return nil, fmt.Errorf("failed to parse spec: %w", err)
		}

		// Validate Spec
		output := Validate(spec)
		if !output.Valid {
			if len(output.Errors) > 0 {
				return nil, fmt.Errorf("validation failed: %s", output.Errors[0].Message)
			}
			return nil, fmt.Errorf("validation failed")
		}

		// Call the typed build function
		return fn(ctx, input, spec)
	}
}

// handleConfigValidate handles the config-validate MCP tool. Beside the
// spec, it holds the entry's declared platforms to this engine's
// Capabilities, so a platform this engine cannot build is refused by
// `forge config validate` and never reaches a build.
func handleConfigValidate(
	_ context.Context,
	_ *mcp.CallToolRequest,
	input mcptypes.ConfigValidateInput,
) (*mcp.CallToolResult, any, error) {
	output := ValidateMap(input.Spec)
	output.Capabilities = Capabilities.Declaration()

	if len(input.Platforms) > 0 {
		if err := engineframework.RefusePlatforms("go-build", Capabilities, input.Platforms); err != nil {
			output.Valid = false
			output.Errors = append(output.Errors, mcptypes.ValidationError{
				Field:   "platforms",
				Message: err.Error(),
			})
		}
	}

	if output.Valid {
		result, artifact := mcputil.SuccessResultWithArtifact(
			"Configuration is valid",
			output,
		)
		return result, artifact, nil
	}

	result, artifact := mcputil.SuccessResultWithArtifact(
		fmt.Sprintf("Configuration validation failed with %d error(s)", len(output.Errors)),
		output,
	)
	return result, artifact, nil
}
