// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:15b760d9d49ca9d416e6e323423f24af9082a7936a0cbecabdd79f0d400d7cff

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-build engine
type Spec struct {
	// Additional arguments to pass to go build (optional)
	Args []string `json:"args,omitempty"`
	// Environment variables to set for the build (optional)
	Env map[string]string `json:"env,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "args":
		case "env":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are args, env", key)
		}
	}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
