// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package mcptypes

import (
	"fmt"
	"strings"

	"github.com/alexandremahdhaoui/forge/pkg/forge"
)

// ConfigValidateInput is the input for the config-validate MCP tool.
// This is sent to engines to validate their specific configuration.
type ConfigValidateInput struct {
	// Spec contains engine-specific configuration to validate.
	// Each engine interprets this according to its own schema.
	Spec map[string]interface{} `json:"spec,omitempty" jsonschema:"Engine-specific configuration to validate"`

	// ForgeSpec is the complete forge.yaml spec.
	// Required for orchestrators (testenv) to access referenced sections
	// like kindenv, localContainerRegistry, etc.
	ForgeSpec *forge.Spec `json:"forgeSpec,omitempty" jsonschema:"Complete forge.yaml spec needed by orchestrators to access referenced sections"`

	// ConfigPath is the path to forge.yaml (for error messages).
	ConfigPath string `json:"configPath,omitempty" jsonschema:"Path to forge.yaml used in error messages"`

	// DirectoryParams contains standardized directory paths.
	// Passed from forge for engines that need path context.
	DirectoryParams *DirectoryParams `json:"directoryParams,omitempty" jsonschema:"Standardized directory paths for engines needing path context"`

	// SpecType indicates which forge.yaml section this spec came from.
	// Values: "build", "test", "testenv"
	// Used for error context.
	SpecType string `json:"specType,omitempty" jsonschema:"Which forge.yaml section this spec came from: build, test, or testenv"`

	// SpecName is the name field from the forge.yaml spec.
	// e.g., "go-app" for a build spec, "unit" for a test spec.
	// Used for error context.
	SpecName string `json:"specName,omitempty" jsonschema:"Name field from the forge.yaml spec entry (e.g. go-app or unit)"`

	// Platforms is what a build entry declares it builds for. A build engine
	// refuses here, before anything compiles, a platform outside what it
	// declares in forge-dev.yaml. Empty for a test or testenv spec.
	Platforms []string `json:"platforms,omitempty" jsonschema:"The os/arch pairs the build entry declares; a build engine refuses those it cannot build"`
}

// ConfigValidateOutput is the output from the config-validate MCP tool.
// This is returned by engines after validating their configuration.
type ConfigValidateOutput struct {
	// Valid is true if the configuration passed all validation checks.
	// Will be false if there are any errors OR if InfraError is non-empty.
	Valid bool `json:"valid"`

	// Errors contains validation errors (if any).
	// Each error should reference the specific field that failed validation.
	Errors []ValidationError `json:"errors,omitempty"`

	// Warnings contains non-fatal validation issues.
	// The configuration is still valid, but may have suboptimal settings.
	Warnings []ValidationWarning `json:"warnings,omitempty"`

	// Capabilities is what the engine declares, answered so a caller learns
	// what it may send: `platforms` (the declared list, or host) and
	// `frozen` (whether the engine reads a frozen input). A build engine
	// generated by forge-dev always answers it; a caller treats an absent
	// block as declaring nothing.
	Capabilities map[string]any `json:"capabilities,omitempty" jsonschema:"What the engine declares it can do: platforms and frozen"`

	// InfraError is non-empty if the engine failed to respond properly.
	// This indicates infrastructure-level failures like:
	// - Engine process failed to spawn
	// - MCP communication timeout
	// - Engine crashed during validation
	// When InfraError is set, Valid should be false.
	InfraError string `json:"infraError,omitempty"`
}

// ValidationError represents a single validation error.
// It provides detailed context about which field failed validation and why.
type ValidationError struct {
	// Field is the JSON path to the invalid field (e.g., "spec.args[0]").
	Field string `json:"field"`

	// Message is a human-readable error description.
	Message string `json:"message"`

	// Engine is the URI of the engine that reported this error.
	// Set by forge during aggregation, not by the engine itself.
	Engine string `json:"engine,omitempty"`

	// SpecType indicates which forge.yaml section contained the error.
	// Values: "build", "test", "testenv"
	// Propagated from ConfigValidateInput.SpecType.
	SpecType string `json:"specType,omitempty"`

	// SpecName is the name of the spec from forge.yaml.
	// Propagated from ConfigValidateInput.SpecName.
	SpecName string `json:"specName,omitempty"`

	// Path provides the full path context from the root of forge.yaml.
	// Each element is a path segment, e.g., ["engines", "2", "testenv", "2", "spec", "charts", "0"].
	// When combined with Field, gives the complete location of the error.
	// Set by orchestrators during aggregation.
	Path []string `json:"path,omitempty"`

	// Nested contains validation errors from sub-engines (recursive validation).
	// For example, testenv may contain errors from testenv-kind, testenv-lcr, etc.
	// This allows preserving the full error tree for detailed diagnostics.
	Nested []ValidationError `json:"nested,omitempty"`
}

// ValidationWarning represents a non-fatal validation issue.
// The configuration is still valid, but there may be suboptimal settings
// or deprecated configurations that should be addressed.
type ValidationWarning struct {
	// Field is the optional JSON path to the relevant field.
	Field string `json:"field,omitempty"`

	// Message is a human-readable warning description.
	Message string `json:"message"`
}

// FullPath returns the complete path to the error, combining Path and Field.
// Example: Path=["engines", "2", "testenv", "1"], Field="spec.charts[0].name"
// Returns: "engines[2].testenv[1].spec.charts[0].name"
func (e ValidationError) FullPath() string {
	var parts []string

	// Build path from Path slice
	for i := 0; i < len(e.Path); i++ {
		segment := e.Path[i]
		// Check if this is an array index (numeric)
		if i > 0 && isNumeric(segment) {
			// Append as array index to previous part
			if len(parts) > 0 {
				parts[len(parts)-1] = parts[len(parts)-1] + "[" + segment + "]"
			}
		} else {
			parts = append(parts, segment)
		}
	}

	// Add the field if present
	if e.Field != "" {
		// Remove "spec." prefix if present since it's redundant with path
		field := strings.TrimPrefix(e.Field, "spec.")
		parts = append(parts, field)
	}

	return strings.Join(parts, ".")
}

// Location returns a human-readable location string.
// Example: "[forge://testenv-helm-install] engines[2].testenv[1].spec.charts[0].name"
func (e ValidationError) Location() string {
	path := e.FullPath()
	if e.Engine != "" {
		if path != "" {
			return fmt.Sprintf("[%s] %s", e.Engine, path)
		}
		return fmt.Sprintf("[%s]", e.Engine)
	}
	return path
}

// String returns a formatted error message with full context.
// Example: "[forge://testenv-helm-install] engines[2].testenv[1].spec.charts[0].name: required field is missing"
func (e ValidationError) String() string {
	loc := e.Location()
	if loc != "" {
		return fmt.Sprintf("%s: %s", loc, e.Message)
	}
	return e.Message
}

// WithPath returns a copy of the error with the path prepended.
// This is used by orchestrators to add context when aggregating errors.
func (e ValidationError) WithPath(pathSegments ...string) ValidationError {
	newPath := make([]string, 0, len(pathSegments)+len(e.Path))
	newPath = append(newPath, pathSegments...)
	newPath = append(newPath, e.Path...)
	e.Path = newPath
	return e
}

// isNumeric checks if a string contains only digits.
func isNumeric(s string) bool {
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return len(s) > 0
}
