package mcptypes

// DirectoryParams contains standardized directory paths passed from forge to engines/runners.
type DirectoryParams struct {
	TmpDir   string `json:"tmpDir,omitempty"`   // Temporary directory for non-build artifacts (e.g., test reports)
	BuildDir string `json:"buildDir,omitempty"` // Build directory for build outputs (e.g., binaries)
	RootDir  string `json:"rootDir,omitempty"`  // Repository root directory (for code generation)
}

// RunInput represents the standard input parameters for test runner tools.
// This is used across all test runners (test-runner-go, generic-test-runner, etc.).
type RunInput struct {
	ID      string            `json:"id"`                // Report ID (UUID, generated by forge and passed to runner)
	Stage   string            `json:"stage"`             // Test stage name (required)
	Name    string            `json:"name"`              // Test name (required)
	Command string            `json:"command,omitempty"` // Command to execute (optional, for generic runner)
	Args    []string          `json:"args,omitempty"`    // Command arguments (optional, for generic runner)
	Env     map[string]string `json:"env,omitempty"`     // Environment variables (optional, for generic runner)
	EnvFile string            `json:"envFile,omitempty"` // Path to environment file (optional, for generic runner)
	WorkDir string            `json:"workDir,omitempty"` // Working directory (optional, for generic runner)

	// Directory parameters (injected by forge)
	DirectoryParams
}

// BuildInput represents the standard input parameters for build engine tools.
// This is used across all build engines (build-go, build-container, generic-engine, etc.).
type BuildInput struct {
	Name   string `json:"name"`           // Artifact name (required)
	Src    string `json:"src,omitempty"`  // Source path
	Dest   string `json:"dest,omitempty"` // Destination path
	Engine string `json:"engine"`         // Engine identifier

	// Generic engine specific fields (optional)
	Command string            `json:"command,omitempty"` // Command to execute
	Args    []string          `json:"args,omitempty"`    // Command arguments
	Env     map[string]string `json:"env,omitempty"`     // Environment variables
	EnvFile string            `json:"envFile,omitempty"` // Path to environment file
	WorkDir string            `json:"workDir,omitempty"` // Working directory

	// Format-go specific fields (optional)
	Path string `json:"path,omitempty"` // Path to format

	// Directory parameters (injected by forge)
	DirectoryParams
}

// BatchBuildInput represents the input for building multiple artifacts in batch.
type BatchBuildInput struct {
	Specs []BuildInput `json:"specs"` // List of build specifications
}
