// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package mcptypes

import (
	"github.com/alexandremahdhaoui/forge/pkg/forge"
)

// DirectoryParams contains standardized directory paths passed from forge to engines/runners.
type DirectoryParams struct {
	TmpDir   string `json:"tmpDir,omitempty" jsonschema:"Temporary directory for non-build artifacts such as test reports"`
	BuildDir string `json:"buildDir,omitempty" jsonschema:"Build output directory for compiled binaries and generated files"`
	RootDir  string `json:"rootDir,omitempty" jsonschema:"Repository root directory used for code generation path resolution"`
}

// RunInput represents the standard input parameters for test runner tools.
// This is used across all test runners (go-test, generic-test-runner, etc.).
type RunInput struct {
	ID      string            `json:"id" jsonschema:"Report ID (UUID) generated by forge and passed to the runner"`
	Stage   string            `json:"stage" jsonschema:"Test stage name matching forge.yaml test[].name"`
	Name    string            `json:"name" jsonschema:"Test name for this run"`
	Command string            `json:"command,omitempty" jsonschema:"Command to execute (generic-test-runner only)"`
	Args    []string          `json:"args,omitempty" jsonschema:"Command arguments (generic-test-runner only)"`
	Env     map[string]string `json:"env,omitempty" jsonschema:"Environment variables as key-value pairs"`
	EnvFile string            `json:"envFile,omitempty" jsonschema:"Path to file containing environment variables"`

	// Artifact files from testenv (e.g., kubeconfig, registry credentials)
	ArtifactFiles map[string]string `json:"artifactFiles,omitempty" jsonschema:"Map of artifact file keys to relative paths from testenv tmpDir"`

	// Testenv tmpDir (where artifact files are located)
	TestenvTmpDir string `json:"testenvTmpDir,omitempty" jsonschema:"Absolute path to the testenv temporary directory containing artifact files"`

	// Testenv metadata (e.g., cluster name, registry URL)
	TestenvMetadata map[string]string `json:"testenvMetadata,omitempty" jsonschema:"Metadata from testenv chain (e.g. cluster name or registry URL)"`

	// Testenv environment variables (propagated from testenv chain)
	TestenvEnv map[string]string `json:"testenvEnv,omitempty" jsonschema:"Environment variables propagated from the testenv chain"`

	// EnvPropagation configuration for filtering testenv environment variables
	EnvPropagation *forge.EnvPropagation `json:"envPropagation,omitempty" jsonschema:"Configuration for filtering which testenv environment variables to propagate"`

	// Spec contains runner-specific configuration (free-form, alternative to individual fields)
	// When present, runners should prefer spec fields over individual Args/Env fields
	// This allows passing configuration from TestSpec.Spec directly through MCP
	//
	// Example for parallel-test-runner engine:
	//   spec: {
	//     "primaryCoverageRunner": "go-test",
	//     "runners": [
	//       {
	//         "name": "go-test",
	//         "engine": "forge://go-test",
	//         "spec": {}
	//       },
	//       {
	//         "name": "go-lint",
	//         "engine": "forge://go-lint",
	//         "spec": {}
	//       }
	//     ]
	//   }
	//
	// Runners define their own Spec structure. See individual runner MCP documentation for details.
	Spec map[string]interface{} `json:"spec,omitempty" jsonschema:"Runner-specific configuration from forge.yaml test[].spec"`

	// Directory parameters (injected by forge)
	DirectoryParams
}

// BuildInput represents the standard input parameters for build engine tools.
// This is used across all build engines (go-build, container-build, generic-builder, etc.).
type BuildInput struct {
	Name    string `json:"name" jsonschema:"Artifact name as defined in forge.yaml build[].name"`
	Src     string `json:"src,omitempty" jsonschema:"Source path relative to project root (e.g. ./cmd/myapp)"`
	Dest    string `json:"dest,omitempty" jsonschema:"Destination path for build output (e.g. ./build/bin)"`
	Context string `json:"context,omitempty" jsonschema:"Resolved absolute path to build context directory"`
	Engine  string `json:"engine" jsonschema:"Engine URI that performs the build (e.g. forge://go-build)"`
	Force   bool   `json:"force,omitempty" jsonschema:"Force rebuild and skip dependency-based caching"`
	Frozen  bool   `json:"frozen,omitempty" jsonschema:"Build strictly against the recorded dependency lock and never repair it; a stale lock fails the build"`

	// Platforms is the os/arch pairs this call must build, one artifact
	// each. Required: the core always names at least one, the host when
	// the build entry declares none, so an engine never guesses. An engine
	// refuses a platform outside what it declares in forge-dev.yaml.
	Platforms []string `json:"platforms" jsonschema:"The os/arch pairs to build (e.g. linux/amd64); required, the core sends the host when the entry declares none"`

	// Generic engine specific fields (optional)
	Command string            `json:"command,omitempty" jsonschema:"Command to execute (generic-builder engine only)"`
	Args    []string          `json:"args,omitempty" jsonschema:"Command arguments (generic-builder engine only)"`
	Env     map[string]string `json:"env,omitempty" jsonschema:"Environment variables as key-value pairs"`
	EnvFile string            `json:"envFile,omitempty" jsonschema:"Path to file containing environment variables"`

	// Format-go specific fields (optional)
	Path string `json:"path,omitempty" jsonschema:"Path to format (go-format engine only)"`

	// Spec contains engine-specific configuration (free-form, alternative to individual fields)
	// When present, engines should prefer spec fields over individual Args/Env fields
	// This allows passing configuration from BuildSpec.Spec directly through MCP
	//
	// Example for go-gen-openapi engine:
	//   spec: {
	//     "sourceFile": "./api/example-api.v1.yaml",
	//     "destinationDir": "./pkg/generated",
	//     "client": {
	//       "enabled": true,
	//       "packageName": "exampleclient"
	//     },
	//     "server": {
	//       "enabled": false
	//     }
	//   }
	//
	// Engines define their own Spec structure. See individual engine MCP documentation for details.
	Spec map[string]interface{} `json:"spec,omitempty" jsonschema:"Engine-specific configuration from forge.yaml build[].spec"`

	// Directory parameters (injected by forge)
	DirectoryParams
}

// BatchBuildInput represents the input for building multiple artifacts in batch.
type BatchBuildInput struct {
	Specs []BuildInput `json:"specs" jsonschema:"List of build specifications to execute in batch"`
}

// BuildOutput is what a build answers: one artifact per platform built, or
// one for an artifact tied to no platform. build and buildBatch answer the
// same shape, so a caller reads one list either way.
type BuildOutput struct {
	Artifacts []forge.Artifact `json:"artifacts" jsonschema:"The artifacts this build produced"`
}

// DetectDependenciesInput represents the standard input parameters for dependency-detector tools.
// This is used across all dependency detectors (go-dependency-detector, etc.).
type DetectDependenciesInput struct {
	FilePath string `json:"filePath"` // Path to source file to analyze (absolute path)
	FuncName string `json:"funcName"` // Name of function to analyze (e.g., "main")

	// Spec contains engine-specific configuration (free-form)
	// The exact fields supported depend on the engine being used
	Spec map[string]interface{} `json:"spec,omitempty"`

	// Directory parameters (injected by forge)
	DirectoryParams
}

// DetectMockDependenciesInput is the input for go-gen-mocks-dep-detector.
type DetectMockDependenciesInput struct {
	RootDir string `json:"rootDir"` // Directory to search for .mockery.yaml
}

// DetectOpenAPIDependenciesInput is the input for go-gen-openapi-dep-detector.
type DetectOpenAPIDependenciesInput struct {
	SpecSources []string `json:"specSources"` // Absolute paths to OpenAPI spec files
	RootDir     string   `json:"rootDir"`     // Project root directory
	ResolveRefs bool     `json:"resolveRefs"` // Whether to resolve $ref (v1: always false)
}

// Dependency represents a single dependency detected by a dependency-detector engine.
// This is the MCP wire format, matching ArtifactDependency from pkg/forge/artifact_store.go.
type Dependency struct {
	// Type is either "file" or "externalPackage"
	Type string `json:"type"`
	// FilePath is the absolute path to file dependency (if Type=file)
	FilePath string `json:"filePath,omitempty"`
	// ExternalPackage is the package identifier (if Type=externalPackage, e.g., "github.com/foo/bar")
	ExternalPackage string `json:"externalPackage,omitempty"`
	// Timestamp is RFC3339 timestamp in UTC (if Type=file, e.g., "2025-11-23T10:00:00Z")
	Timestamp string `json:"timestamp,omitempty"`
	// Semver is semantic version (if Type=externalPackage, supports pseudo-versions like "v0.0.0-20231010123456-abcdef123456")
	Semver string `json:"semver,omitempty"`
}

// DetectDependenciesOutput represents the output from dependency-detector tools.
type DetectDependenciesOutput struct {
	Dependencies []Dependency `json:"dependencies"` // List of detected dependencies
}
