// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:be2a72c9ee9573ce227f96d1b1763c8d12c72ea9b2ac2f42f2146cb1e7ff24b3

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-gen-openapi-dep-detector
type Spec struct {
	// Whether to resolve external references
	ResolveRefs bool `json:"resolveRefs,omitempty"`
	// Root directory for resolving relative paths
	RootDir string `json:"rootDir,omitempty"`
	// OpenAPI spec file paths to scan
	SpecSources []string `json:"specSources,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "resolveRefs":
		case "rootDir":
		case "specSources":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are resolveRefs, rootDir, specSources", key)
		}
	}
	// Parse resolveRefs
	if v, ok := m["resolveRefs"]; ok && v != nil {
		if val, ok := v.(bool); ok {
			s.ResolveRefs = val
		} else {
			return nil, fmt.Errorf("field resolveRefs: expected bool, got %T", v)
		}
	}
	// Parse rootDir
	if v, ok := m["rootDir"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.RootDir = val
		} else {
			return nil, fmt.Errorf("field rootDir: expected string, got %T", v)
		}
	}
	// Parse specSources
	if v, ok := m["specSources"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.SpecSources = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.SpecSources = append(s.SpecSources, str)
				} else {
					return nil, fmt.Errorf("field specSources[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.SpecSources = arr
		} else {
			return nil, fmt.Errorf("field specSources: expected []string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.ResolveRefs {
		m["resolveRefs"] = s.ResolveRefs
	}
	if s.RootDir != "" {
		m["rootDir"] = s.RootDir
	}
	if len(s.SpecSources) > 0 {
		m["specSources"] = s.SpecSources
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
