//go:build unit

// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"context"
	"log"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/alexandremahdhaoui/forge/pkg/mcptypes"
	"github.com/stretchr/testify/require"
)

func answerWith(paths ...string) map[string]interface{} {
	files := []interface{}{}
	for _, path := range paths {
		files = append(files, map[string]interface{}{"path": path, "content": "// " + path + "\n"})
	}

	return map[string]interface{}{"files": files}
}

func answerFiles(files ...map[string]interface{}) map[string]interface{} {
	entries := []interface{}{}
	for _, file := range files {
		entries = append(entries, file)
	}

	return map[string]interface{}{"files": entries}
}

func headeredFileWith(prefix, path string) map[string]interface{} {
	return map[string]interface{}{
		"path":    path,
		"content": prefix + " Code generated by gui-gen (forge-dev-codegen). DO NOT EDIT.\n",
	}
}

func headeredFile(path string) map[string]interface{} {
	return headeredFileWith("//", path)
}

func headerlessFile(path string) map[string]interface{} {
	return map[string]interface{}{"path": path, "content": "pub mod hand;\n"}
}

func generateCell(t *testing.T, dir string, answer map[string]interface{}) error {
	t.Helper()

	stub := &stubGeneratorCaller{answer: answer}
	withStubGenerator(t, stub)

	_, err := generate(context.Background(), mcptypes.BuildInput{
		Name: "fixture-gui", Src: dir, Engine: "forge://forge-dev",
	})

	return err
}

func TestAnAnsweredPathThatIsNotNamedZzGeneratedFailsNamingThePathAndTheGenerator(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	err := generateCell(t, dir, answerWith("src/hand_written.rs"))

	require.Error(t, err)
	require.Contains(t, err.Error(), "src/hand_written.rs is not named zz_generated")
	require.Contains(t, err.Error(), "forge://example.com/org/gui-gen/engines/gui-gen")
}

func TestEveryLanguageModuleRootWithTheGeneratedHeaderOnLineOneIsAccepted(t *testing.T) {
	for _, testCase := range []struct {
		name   string
		prefix string
		path   string
	}{
		{"a rust mod.rs is accepted", "//", "src/grpc/mod.rs"},
		{"a rust lib.rs is accepted", "//", "src/lib.rs"},
		{"a rust main.rs is accepted", "//", "src/main.rs"},
		{"a python __init__.py with a hash header is accepted", "#", "src/pkg/__init__.py"},
		{"a typescript index.ts is accepted", "//", "src/index.ts"},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			dir := t.TempDir()
			writeKindFixture(t, dir, customKindYaml())

			answer := answerFiles(headeredFileWith(testCase.prefix, testCase.path))

			require.NoError(t, generateCell(t, dir, answer))
			require.FileExists(t, filepath.Join(dir, filepath.FromSlash(testCase.path)))
		})
	}
}

func TestAModuleRootWithoutTheGeneratedHeaderIsRefusedNamingThePath(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	err := generateCell(t, dir, answerFiles(headerlessFile("src/grpc/mod.rs")))

	require.Error(t, err)
	require.Contains(t, err.Error(),
		"the module root src/grpc/mod.rs is missing the generated header on line one")
	require.NoFileExists(t, filepath.Join(dir, "src", "grpc", "mod.rs"))
}

func TestAStaleModuleRootWithTheGeneratedHeaderIsSweptOnTheNextRun(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerFiles(
		headeredFile("zz_generated_a.rs"), headeredFile("src/grpc/lib.rs"))))
	require.FileExists(t, filepath.Join(dir, "src", "grpc", "lib.rs"))

	require.NoError(t, generateCell(t, dir, answerFiles(headeredFile("zz_generated_a.rs"))))

	require.NoFileExists(t, filepath.Join(dir, "src", "grpc", "lib.rs"))
}

func TestAPathThatIsNotAModuleRootIsRefusedEvenWithTheGeneratedHeader(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	err := generateCell(t, dir, answerFiles(headeredFile("src/hand_written.rs")))

	require.Error(t, err)
	require.Contains(t, err.Error(), "src/hand_written.rs is not named zz_generated")
	require.NoFileExists(t, filepath.Join(dir, "src", "hand_written.rs"))
}

func TestAnAnsweredPathInASubdirectoryIsJudgedOnItsBasename(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("src/rest/zz_generated_driver.rs")))
	require.FileExists(t, filepath.Join(dir, "src", "rest", "zz_generated_driver.rs"))
}

func TestTheRunnableManifestRecordsEveryPathTheGeneratorAnswered(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs", "src/zz_generated_b.rs")))

	recorded, err := ReadGeneratedFiles(filepath.Join(dir, GeneratedRunnableFile))
	require.NoError(t, err)
	require.Equal(t, []string{"zz_generated_a.rs", "src/zz_generated_b.rs"}, recorded)
}

func TestAFileTheNewAnswerDoesNotHoldIsRemovedOnTheNextRun(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs", "zz_generated_b.rs")))
	require.FileExists(t, filepath.Join(dir, "zz_generated_b.rs"))

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	require.FileExists(t, filepath.Join(dir, "zz_generated_a.rs"))
	require.NoFileExists(t, filepath.Join(dir, "zz_generated_b.rs"))

	recorded, err := ReadGeneratedFiles(filepath.Join(dir, GeneratedRunnableFile))
	require.NoError(t, err)
	require.Equal(t, []string{"zz_generated_a.rs"}, recorded)
}

func TestAStaleFileAlreadyGoneLeavesTheRunQuiet(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs", "zz_generated_b.rs")))
	require.NoError(t, os.Remove(filepath.Join(dir, "zz_generated_b.rs")))

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))
}

func TestAGeneratorThatDeclaresAManifestAndAnswersNoneFailsNamingTheGenerator(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	answer := answerWith("zz_generated_a.rs")
	answer["manifest"] = true

	err := generateCell(t, dir, answer)

	require.Error(t, err)
	require.Contains(t, err.Error(), GeneratedCellManifestFile)
	require.Contains(t, err.Error(), "forge://example.com/org/gui-gen/engines/gui-gen")
}

func TestAGeneratorThatDeclaresAManifestAndAnswersOneIsAccepted(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	answer := answerWith("zz_generated_a.rs", "src/rest/"+GeneratedCellManifestFile)
	answer["manifest"] = true

	require.NoError(t, generateCell(t, dir, answer))
	require.FileExists(t, filepath.Join(dir, "src", "rest", GeneratedCellManifestFile))
}

func TestAGeneratorThatDeclaresNoManifestNeedsNone(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))
}

func TestARefusedAnswerWritesNothing(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	err := generateCell(t, dir, answerWith("zz_generated_a.rs", "src/hand_written.rs"))

	require.Error(t, err)
	require.NoFileExists(t, filepath.Join(dir, "zz_generated_a.rs"))
	require.NoFileExists(t, filepath.Join(dir, "src", "hand_written.rs"))
}

func TestARecordedEntryThatEscapesTheEngineDirectoryIsSkippedInsteadOfRemoved(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "deep", "cell")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	writeKindFixture(t, dir, customKindYaml())

	outside := filepath.Join(root, "x")
	require.NoError(t, os.WriteFile(outside, []byte("mine\n"), 0o644))

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	runnable := filepath.Join(dir, GeneratedRunnableFile)
	raw, err := os.ReadFile(runnable)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(runnable, []byte(string(raw)+"  - ../../x\n"), 0o644))

	logged := captureLog(t)

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	require.FileExists(t, outside)
	require.Contains(t, logged.String(),
		"forge-dev: skipped the recorded entry ../../x, it is not removable, "+
			"it must be named zz_generated or be a module root carrying the generated header, "+
			"and stay inside the engine directory")
}

func recordExtraGeneratedEntry(t *testing.T, dir, entry string) {
	t.Helper()

	runnable := filepath.Join(dir, GeneratedRunnableFile)

	raw, err := os.ReadFile(runnable)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(runnable, []byte(string(raw)+"  - "+entry+"\n"), 0o644))
}

func TestAStaleModuleRootWithoutTheGeneratedHeaderIsSkippedInsteadOfRemoved(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	handWritten := filepath.Join(dir, "src", "lib.rs")
	require.NoError(t, os.MkdirAll(filepath.Dir(handWritten), 0o755))
	require.NoError(t, os.WriteFile(handWritten, []byte("pub mod hand;\n"), 0o644))

	recordExtraGeneratedEntry(t, dir, "src/lib.rs")

	logged := captureLog(t)

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	require.FileExists(t, handWritten)
	require.Contains(t, logged.String(),
		"forge-dev: skipped the recorded entry src/lib.rs, it is not removable, "+
			"it must be named zz_generated or be a module root carrying the generated header, "+
			"and stay inside the engine directory")
}

func TestAStaleModuleRootAlreadyGoneStaysRemovable(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	recordExtraGeneratedEntry(t, dir, "src/lib.rs")

	logged := captureLog(t)

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	require.NoFileExists(t, filepath.Join(dir, "src", "lib.rs"))
	require.Contains(t, logged.String(), "forge-dev: removed the stale generated file src/lib.rs")
	require.NotContains(t, logged.String(), "skipped the recorded entry src/lib.rs")
}

func TestACellWithNoGeneratorSweepsNothing(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, coreCellYaml())

	_, err := generate(context.Background(), mcptypes.BuildInput{
		Name: "plain-tool", Src: dir, Engine: "forge://forge-dev",
	})
	require.NoError(t, err)

	planted := filepath.Join(dir, "zz_generated_planted.go")
	require.NoError(t, os.WriteFile(planted, []byte("// planted\n"), 0o644))

	runnable := filepath.Join(dir, GeneratedRunnableFile)
	raw, err := os.ReadFile(runnable)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(
		runnable, []byte(string(raw)+"files:\n  - zz_generated_planted.go\n"), 0o644))

	recorded, err := ReadGeneratedFiles(runnable)
	require.NoError(t, err)
	require.Equal(t, []string{"zz_generated_planted.go"}, recorded)

	_, err = generate(context.Background(), mcptypes.BuildInput{
		Name: "plain-tool", Src: dir, Engine: "forge://forge-dev",
	})
	require.NoError(t, err)

	require.FileExists(t, planted)
}

func coreCellYaml() string {
	return `name: plain-tool
kind: binary
version: 0.1.0
openapi:
  specPath: ./spec.openapi.yaml
generate:
  packageName: main
  docsBaseURL: https://example.com/raw
`
}

func captureLog(t *testing.T) *strings.Builder {
	t.Helper()

	var logged strings.Builder

	previousOutput := log.Writer()
	log.SetOutput(&logged)
	t.Cleanup(func() { log.SetOutput(previousOutput) })

	return &logged
}

func TestAFileTheUserWroteInTheCellSurvivesEveryRun(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	handWritten := filepath.Join(dir, "src", "hand", "mine.rs")
	require.NoError(t, os.MkdirAll(filepath.Dir(handWritten), 0o755))
	require.NoError(t, os.WriteFile(handWritten, []byte("fn mine() {}\n"), 0o644))

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs", "zz_generated_b.rs")))
	require.FileExists(t, handWritten)

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))
	require.FileExists(t, handWritten)

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_c.rs")))
	require.FileExists(t, handWritten)
}

func TestAFirstRunWithNoRecordedListRemovesNothing(t *testing.T) {
	dir := t.TempDir()
	writeKindFixture(t, dir, customKindYaml())

	neighbor := filepath.Join(dir, "zz_generated_stray.rs")
	require.NoError(t, os.WriteFile(neighbor, []byte("// stray\n"), 0o644))

	recorded, err := ReadGeneratedFiles(filepath.Join(dir, GeneratedRunnableFile))
	require.NoError(t, err)
	require.Empty(t, recorded)

	require.NoError(t, generateCell(t, dir, answerWith("zz_generated_a.rs")))

	require.FileExists(t, neighbor)
	require.FileExists(t, filepath.Join(dir, "zz_generated_a.rs"))
}
