// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:38fcde5f565edc32f1c8c698ad9ba0a544fbff6be5fbecb054f9be8bd13aa3f6

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for forge-e2e test runner.
type Spec struct {
	// Filter tests by category (build, testenv, test-runner, prompt, system, error, cleanup, mcp, performance, artifact-store)
	Category string `json:"category,omitempty"`
	// Filter tests by name pattern (case-insensitive substring match)
	NamePattern string `json:"namePattern,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "category":
		case "namePattern":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are category, namePattern", key)
		}
	}
	// Parse category
	if v, ok := m["category"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Category = val
		} else {
			return nil, fmt.Errorf("field category: expected string, got %T", v)
		}
	}
	// Parse namePattern
	if v, ok := m["namePattern"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.NamePattern = val
		} else {
			return nil, fmt.Errorf("field namePattern: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.Category != "" {
		m["category"] = s.Category
	}
	if s.NamePattern != "" {
		m["namePattern"] = s.NamePattern
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
