// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:4da63cb64468730a0d536f8c54eb5448e86e54a93970bed77bcd8ba9687d100e

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for go-gen-openapi. Uses oapi-codegen for code generation.
type Spec struct {
	// Version of oapi-codegen to use (default v2.3.0)
	OapiCodegenVersion string `json:"oapiCodegenVersion,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "oapiCodegenVersion":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are oapiCodegenVersion", key)
		}
	}
	// Parse oapiCodegenVersion
	if v, ok := m["oapiCodegenVersion"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.OapiCodegenVersion = val
		} else {
			return nil, fmt.Errorf("field oapiCodegenVersion: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if s.OapiCodegenVersion != "" {
		m["oapiCodegenVersion"] = s.OapiCodegenVersion
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
