// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/alexandremahdhaoui/forge/internal/orchestrate"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
)

// BuildAllResult contains the outcome of a build operation.
// Both CLI and MCP use this struct to communicate build results.
type BuildAllResult struct {
	Artifacts   []forge.Artifact
	Skipped     int
	TotalBuilt  int
	BuildErrors []string
}

// engineGroup is one run of consecutive same-engine build specs.
type engineGroup struct {
	engine string
	specs  []map[string]any
}

// appendSpecToGroups adds params under engine, opening a new group only
// when the engine changes. A global per-engine map ran engine batches in
// random order, so a file generated by one engine raced the batch that
// consumed it on a cold cache; the declared order is the author's
// ordering contract and it survives here.
func appendSpecToGroups(groups []engineGroup, engine string, params map[string]any) []engineGroup {
	if len(groups) > 0 && groups[len(groups)-1].engine == engine {
		groups[len(groups)-1].specs = append(groups[len(groups)-1].specs, params)

		return groups
	}

	return append(groups, engineGroup{engine: engine, specs: []map[string]any{params}})
}

// buildAll loads config, resolves context, checks lazy rebuild,
// dispatches to engines, and updates the artifact store.
// Both CLI and MCP call this function.
//
// artifactName filters to a single artifact if non-empty.
// forceRebuild bypasses lazy rebuild checks.
//
// This function MUST NOT write to stdout. Stdout is the JSON-RPC
// transport in MCP mode. Progress messages go to stderr.

// buildPlatforms is the os/arch list `forge build --platforms` asked for. It
// is a filter over what entries DECLARE and nothing more: an entry builds
// the platforms it declares, narrowed to these when they are set, and an
// entry that declares none is a host build outside any platform selection.
// Empty means everything, each entry for what it declares or the host.
var buildPlatforms []string

// hostPlatform is the machine this forge runs on, which is what an entry
// that declares no platform builds for.
func hostPlatform() string {
	return runtime.GOOS + "/" + runtime.GOARCH
}

// platformsFor answers what one entry builds this time: every platform it
// declares - the host when it declares none - narrowed to the requested
// subset when one was asked for. Nothing is inferred: the entry declares,
// the flag selects, the host is the one fact the machine states.
//
// The flag selects among declarations only. An entry that declares no
// platform is a host build - a repo's own tool, a test fixture, an image
// that wants a daemon - and a platform selection is not about it, even
// when the host happens to be one of the platforms named: a distribution
// build names its platforms and gets exactly what declared them, never a
// tool that travels because the runner is the same machine.
func platformsFor(spec forge.BuildSpec, wanted []string) []string {
	declared := spec.Platforms
	if len(declared) == 0 {
		if len(wanted) > 0 {
			return nil
		}

		declared = []string{hostPlatform()}
	}

	if len(wanted) == 0 {
		return declared
	}

	out := []string{}

	for _, platform := range declared {
		for _, w := range wanted {
			if w == platform {
				out = append(out, platform)

				break
			}
		}
	}

	return out
}

func buildAll(artifactName string, forceRebuild, frozenBuild bool) (*BuildAllResult, error) {
	// Load forge.yaml configuration
	config, err := loadConfig()
	if err != nil {
		return nil, fmt.Errorf("failed to load forge.yaml: %w", err)
	}

	// Read artifact store
	store, err := forge.ReadOrCreateArtifactStore(config.ArtifactStorePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read artifact store: %w", err)
	}

	// Group consecutive same-engine specs, preserving declaration order.
	var groups []engineGroup
	result := &BuildAllResult{}

	// Track cleanup functions for git-cloned context directories.
	// Temp dirs must persist until all engine builds complete because specs
	// are grouped by engine and sent as a batch -- cleanup after all builds.
	var cleanups []func()
	defer func() {
		for _, fn := range cleanups {
			fn()
		}
	}()

	matched := 0

	for _, spec := range config.Build {
		if artifactName != "" && spec.Name != artifactName {
			continue
		}

		matched++

		// What this entry builds this time. A subset filter that leaves an
		// entry with nothing is a skip, not an error: `--platforms linux/arm64`
		// over a repo whose own tool declares no platform builds the tools
		// that declared it and leaves the rest home. Only a filter that
		// matches nothing at all is an error, below.
		platforms := platformsFor(spec, buildPlatforms)
		if len(platforms) == 0 {
			fmt.Fprintf(os.Stderr, "⏭  Skipping %s (declares none of %s)\n", spec.Name, strings.Join(buildPlatforms, ", "))

			continue
		}

		// Check if rebuild is needed (lazy rebuild logic), per platform: a
		// host binary that is fresh says nothing about the arm64 one.
		needsRebuild, reason, err := shouldRebuild(spec.Name, platforms, store, forceRebuild)
		if err != nil {
			// If error checking rebuild status, log warning and rebuild (safe default)
			fmt.Fprintf(os.Stderr, "Warning: failed to check rebuild status for %s: %v (will rebuild)\n", spec.Name, err)
			needsRebuild = true
			reason = "rebuild check failed"
		}

		if !needsRebuild {
			// Skip this artifact - it's up to date
			fmt.Fprintf(os.Stderr, "⏭  Skipping %s (unchanged)\n", spec.Name)
			result.Skipped++
			continue
		}

		// Log reason for rebuild if provided
		if reason != "" {
			fmt.Fprintf(os.Stderr, "🔨 Building %s (%s)\n", spec.Name, reason)
		}

		// Normalize engine URI and warn if deprecated
		normalizedEngine, wasDeprecated := normalizeEngineURI(spec.Engine)
		if wasDeprecated {
			fmt.Fprintf(os.Stderr,
				"⚠️  DEPRECATED: %s is deprecated, use %s instead (in spec: %s)\n",
				spec.Engine, normalizedEngine, spec.Name)
		}

		// Use the normalized engine
		engine := normalizedEngine

		// Resolve build context
		contextDir, cleanup, err := resolveContextDir(spec.Context)
		if err != nil {
			return nil, fmt.Errorf("failed to resolve context for %s: %w", spec.Name, err)
		}
		cleanups = append(cleanups, cleanup)

		// Resolve src relative to context directory.
		// Only join if spec.Src is relative AND context is explicitly set.
		resolvedSrc := spec.Src
		if spec.Context != "" && spec.Context != "." && !filepath.IsAbs(spec.Src) {
			resolvedSrc = filepath.Join(contextDir, spec.Src)
		}

		params := map[string]any{
			"name":      spec.Name,
			"src":       resolvedSrc,
			"dest":      spec.Dest,
			"context":   contextDir,
			"engine":    engine,
			"platforms": platforms,
		}

		// Pass engine-specific configuration if provided
		// Nest under "spec" key so engines can access it via BuildInput.Spec
		if len(spec.Spec) > 0 {
			params["spec"] = spec.Spec
		}

		groups = appendSpecToGroups(groups, engine, params)
	}

	if artifactName != "" && matched == 0 {
		return nil, fmt.Errorf("no artifact found with name: %s", artifactName)
	}

	if len(groups) == 0 {
		if len(buildPlatforms) > 0 && result.Skipped == 0 {
			return nil, fmt.Errorf(
				"no artifact declares any of the platforms %s; an artifact builds only the platforms its own build entry names",
				strings.Join(buildPlatforms, ", "))
		}

		// Either all skipped or no artifacts to build
		return result, nil
	}

	// Create forge directories for build operations
	dirs, err := createForgeDirs()
	if err != nil {
		return nil, fmt.Errorf("failed to create forge directories: %w", err)
	}

	// Clean up old tmp directories (keep last 10 runs)
	if err := cleanupOldTmpDirs(10); err != nil {
		// Log warning but don't fail
		fmt.Fprintf(os.Stderr, "Warning: failed to cleanup old tmp directories: %v\n", err)
	}

	// Build each group in declaration order using the appropriate engine
	for _, group := range groups {
		engineURI, specs := group.engine, group.specs
		fmt.Fprintf(os.Stderr, "Building %d artifact(s) with %s...\n", len(specs), engineURI)

		// Check if this is a multi-engine alias
		var artifacts []forge.Artifact
		if strings.HasPrefix(engineURI, "alias://") {
			aliasName := strings.TrimPrefix(engineURI, "alias://")
			engineConfig := getEngineConfig(aliasName, &config)
			if engineConfig == nil {
				result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("engine alias not found: %s", aliasName))
				continue
			}

			if engineConfig.Type == forge.BuilderEngineConfigType && len(engineConfig.Builder) > 1 {
				// Multi-engine builder - use orchestrator
				fmt.Fprintf(os.Stderr, "  Multi-engine builder detected (%d engines)\n", len(engineConfig.Builder))

				orchestrator := orchestrate.NewBuilderOrchestrator(
					callMCPEngine,
					func(uri string) (string, []string, error) {
						return resolveEngine(uri, &config)
					},
				)

				// Prepare directories map
				dirsMap := map[string]any{
					"tmpDir":   dirs.TmpDir,
					"buildDir": dirs.BuildDir,
					"rootDir":  dirs.RootDir,
				}

				// Execute orchestration
				artifacts, err = orchestrator.Orchestrate(engineConfig.Builder, specs, dirsMap)
				if err != nil {
					result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("multi-engine build failed: %v", err))
					continue
				}
			} else {
				// Single-engine alias - resolve to actual engine
				command, args, err := resolveEngine(engineURI, &config)
				if err != nil {
					result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("failed to resolve engine %s: %v", engineURI, err))
					continue
				}

				artifacts, err = buildWithSingleEngine(command, args, specs, dirs, engineConfig, forceRebuild, frozenBuild)
				if err != nil {
					result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("build failed for %s: %v", engineURI, err))
					continue
				}
			}
		} else {
			// Direct forge:// URI - single engine
			command, args, err := resolveEngine(engineURI, &config)
			if err != nil {
				result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("failed to resolve engine %s: %v", engineURI, err))
				continue
			}

			artifacts, err = buildWithSingleEngine(command, args, specs, dirs, nil, forceRebuild, frozenBuild)
			if err != nil {
				result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("build failed for %s: %v", engineURI, err))
				continue
			}
		}

		// Update artifact store
		for _, artifact := range artifacts {
			forge.AddOrUpdateArtifact(&store, artifact)
			result.Artifacts = append(result.Artifacts, artifact)
			result.TotalBuilt++
		}

		// Written after every group, not once at the end: a later entry may
		// read this repository's own records (an image assembled from the
		// binaries the entries before it built), and it reads them from the
		// file. Held in memory until the end, the store did not exist on a
		// fresh clone when that entry ran, and it failed on its own repo.
		if err := forge.WriteArtifactStore(config.ArtifactStorePath, store); err != nil {
			return nil, fmt.Errorf("failed to write artifact store: %w", err)
		}
	}

	// If there were build errors, return them as an error
	if len(result.BuildErrors) > 0 {
		return result, fmt.Errorf("build completed with errors: %v", result.BuildErrors)
	}

	return result, nil
}

// normalizeEngineURI maps deprecated engine URIs to their current equivalents.
// Returns the normalized URI and whether a deprecated URI was used.
func normalizeEngineURI(uri string) (string, bool) {
	deprecated := map[string]string{
		"forge://build-container": "forge://container-build",
	}

	if newURI, ok := deprecated[uri]; ok {
		return newURI, true // deprecated
	}

	return uri, false // not deprecated
}

// shouldRebuild determines if an artifact needs to be rebuilt, for every
// platform the entry builds this time. Returns (needsRebuild bool, reason
// string, error). If forceRebuild is true, always returns (true, "force flag
// set", nil). Otherwise the first platform whose record is missing or
// stale decides, because one engine call builds them all.
func shouldRebuild(artifactName string, platforms []string, store forge.ArtifactStore, forceRebuild bool) (bool, string, error) {
	// Step 1: If forceRebuild is true, always rebuild
	if forceRebuild {
		return true, "force flag set", nil
	}

	for _, platform := range platforms {
		rebuild, reason, err := platformNeedsRebuild(artifactName, platform, store)
		if err != nil || rebuild {
			return rebuild, reason, err
		}
	}

	// If all dependencies unchanged, no rebuild needed
	return false, "", nil
}

// platformNeedsRebuild is the freshness of one artifact record: the one the
// store holds for this name and platform, or, for an entry whose engine
// builds nothing platform-tied - a generator, a formatter - the record it
// holds under no platform.
func platformNeedsRebuild(artifactName, platform string, store forge.ArtifactStore) (bool, string, error) {
	// Step 2: Look up latest artifact for artifactName in store
	artifact, err := forge.GetLatestArtifact(store, artifactName, platform)
	if err != nil {
		artifact, err = forge.GetLatestArtifact(store, artifactName, "")
	}

	if err != nil {
		// Step 3: If no artifact found, rebuild
		return true, "no previous build for " + platform, nil
	}

	// Step 4: Check if artifact location still exists on filesystem
	if _, err := os.Stat(strings.TrimPrefix(artifact.Location, "file://")); os.IsNotExist(err) {
		return true, "artifact file missing for " + platform, nil
	} else if err != nil {
		// If stat fails for other reason, assume rebuild needed
		return true, fmt.Sprintf("cannot access artifact file: %v", err), nil
	}

	// Step 5: If artifact has no Dependencies field (nil or empty)
	if len(artifact.Dependencies) == 0 {
		return true, "dependencies not tracked", nil
	}

	// Step 7: If artifact has no DependencyDetectorEngine, rebuild
	if artifact.DependencyDetectorEngine == "" {
		return true, "dependency detector not configured", nil
	}

	// Step 6: Compare using STORED dependencies ONLY (DO NOT re-detect)
	manifestTracked := false
	for _, dep := range artifact.Dependencies {
		if dep.Type == forge.DependencyTypeFile {
			// Check if the module manifest is tracked
			if strings.HasSuffix(dep.FilePath, "go.mod") {
				manifestTracked = true
			}

			// Check if file still exists
			fileInfo, err := os.Stat(dep.FilePath)
			if os.IsNotExist(err) {
				return true, fmt.Sprintf("dependency file %s missing", dep.FilePath), nil
			} else if err != nil {
				// If stat fails for other reason, assume changed (safe default)
				return true, fmt.Sprintf("cannot access dependency file %s: %v", dep.FilePath, err), nil
			}

			// Get current timestamp and format as RFC3339 UTC
			currentTimestamp := fileInfo.ModTime().UTC().Format(time.RFC3339)

			// Parse stored timestamp
			storedTime, err := time.Parse(time.RFC3339, dep.Timestamp)
			if err != nil {
				// Parse error - assume changed (safe default)
				return true, fmt.Sprintf("dependency %s timestamp parse error", dep.FilePath), nil
			}

			// Parse current timestamp
			currentTime, err := time.Parse(time.RFC3339, currentTimestamp)
			if err != nil {
				// Parse error - assume changed (safe default)
				return true, fmt.Sprintf("dependency %s current timestamp parse error", dep.FilePath), nil
			}

			// Compare timestamps using .Equal()
			if !currentTime.Equal(storedTime) {
				return true, fmt.Sprintf("dependency %s modified", dep.FilePath), nil
			}
		}
		// External package dependencies: DO NOT re-parse the manifest
		// External packages are considered unchanged (semver only changes if the manifest changes)
	}

	// If the manifest is NOT in file dependencies and we have external package dependencies
	hasExternalDeps := false
	for _, dep := range artifact.Dependencies {
		if dep.Type == forge.DependencyTypeExternalPackage {
			hasExternalDeps = true
			break
		}
	}
	if hasExternalDeps && !manifestTracked {
		// Log warning once (don't fail build)
		fmt.Fprintf(os.Stderr, "Warning: the module manifest is not tracked as a dependency for %s, external package changes may not trigger rebuild\n", artifactName)
	}

	return false, "", nil
}

// buildWithSingleEngine handles building with a single engine (either direct forge:// URI or single-engine alias).
func buildWithSingleEngine(
	command string,
	args []string,
	specs []map[string]any,
	dirs *ForgeDirs,
	engineConfig *forge.EngineConfig,
	forceRebuild bool,
	frozenBuild bool,
) ([]forge.Artifact, error) {
	// Prepare specs with injected directories and config
	specsWithConfig := make([]map[string]any, len(specs))
	for i, spec := range specs {
		// Clone the spec
		clonedSpec := make(map[string]any)
		for k, v := range spec {
			clonedSpec[k] = v
		}

		// Inject directories
		clonedSpec["tmpDir"] = dirs.TmpDir
		clonedSpec["buildDir"] = dirs.BuildDir
		clonedSpec["rootDir"] = dirs.RootDir

		// Inject force rebuild flag
		clonedSpec["force"] = forceRebuild

		// Inject the frozen flag: a real build proves the recorded lock and
		// never repairs it, so a stale lock fails instead of self-healing
		// into a build nobody can reproduce.
		clonedSpec["frozen"] = frozenBuild

		// Inject engine-specific config if provided (from alias)
		// For generic engines, promote spec fields to top level for backward compatibility
		if engineConfig != nil && engineConfig.Type == forge.BuilderEngineConfigType && len(engineConfig.Builder) > 0 {
			builderSpec := engineConfig.Builder[0].Spec
			if builderSpec.Command != "" {
				clonedSpec["command"] = builderSpec.Command
			}
			if len(builderSpec.Args) > 0 {
				clonedSpec["args"] = builderSpec.Args
			}
			if len(builderSpec.Env) > 0 {
				clonedSpec["env"] = builderSpec.Env
			}
			if builderSpec.EnvFile != "" {
				clonedSpec["envFile"] = builderSpec.EnvFile
			}
			if builderSpec.Context != "" {
				clonedSpec["context"] = builderSpec.Context
			}
		} else if nestedSpec, ok := spec["spec"].(map[string]interface{}); ok {
			// Keep the spec nested - engines expect it in input.Spec
			// Convert to map[string]any for consistency
			specMap := make(map[string]any)
			for k, v := range nestedSpec {
				specMap[k] = v
			}
			clonedSpec["spec"] = specMap
		}

		specsWithConfig[i] = clonedSpec
	}

	// Call MCP engine (use build for single spec, buildBatch for multiple)
	var mcpResult interface{}
	var err error
	if len(specsWithConfig) == 1 {
		mcpResult, err = callMCPEngine(command, args, "build", specsWithConfig[0])
	} else {
		params := map[string]any{
			"specs": specsWithConfig,
		}
		mcpResult, err = callMCPEngine(command, args, "buildBatch", params)
	}

	if err != nil {
		return nil, err
	}

	// Parse and return artifacts
	artifacts, err := parseArtifacts(mcpResult)
	if err != nil {
		return nil, err
	}

	return artifacts, nil
}

// parseArtifacts converts MCP result to forge.Artifact slice.
func parseArtifacts(result interface{}) ([]forge.Artifact, error) {
	// Result could be:
	// 1. A single artifact object
	// 2. An array of artifacts
	// 3. A BatchResult object (from buildBatch) containing an artifacts array

	// Try to convert to JSON and back to parse it
	data, err := json.Marshal(result)
	if err != nil {
		return nil, err
	}

	// Try parsing as BatchResult first (from buildBatch operations)
	type BatchResult struct {
		Artifacts []forge.Artifact `json:"artifacts"`
	}
	var batchResult BatchResult
	if err := json.Unmarshal(data, &batchResult); err == nil && len(batchResult.Artifacts) > 0 {
		return batchResult.Artifacts, nil
	}

	// Try parsing as single artifact
	var singleArtifact forge.Artifact
	if err := json.Unmarshal(data, &singleArtifact); err == nil && singleArtifact.Name != "" {
		return []forge.Artifact{singleArtifact}, nil
	}

	// Try parsing as array of artifacts
	var multipleArtifacts []forge.Artifact
	if err := json.Unmarshal(data, &multipleArtifacts); err == nil {
		return multipleArtifacts, nil
	}

	return nil, fmt.Errorf("could not parse artifacts from result")
}
