// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/alexandremahdhaoui/forge/internal/orchestrate"
	"github.com/alexandremahdhaoui/forge/pkg/forge"
)

// BuildAllResult contains the outcome of a build operation.
// Both CLI and MCP use this struct to communicate build results.
type BuildAllResult struct {
	Artifacts   []forge.Artifact
	Skipped     int
	TotalBuilt  int
	BuildErrors []string
}

// engineGroup is one run of consecutive same-engine build specs.
type engineGroup struct {
	engine string
	specs  []map[string]any
}

// appendSpecToGroups adds params under engine, opening a new group only
// when the engine changes. A global per-engine map ran engine batches in
// random order, so a file generated by one engine raced the batch that
// consumed it on a cold cache; the declared order is the author's
// ordering contract and it survives here.
func appendSpecToGroups(groups []engineGroup, engine string, params map[string]any) []engineGroup {
	if len(groups) > 0 && groups[len(groups)-1].engine == engine {
		groups[len(groups)-1].specs = append(groups[len(groups)-1].specs, params)

		return groups
	}

	return append(groups, engineGroup{engine: engine, specs: []map[string]any{params}})
}

// buildAll loads config, resolves context, checks lazy rebuild,
// dispatches to engines, and updates the artifact store.
// Both CLI and MCP call this function.
//
// artifactName filters to a single artifact if non-empty.
//
// This function MUST NOT write to stdout. Stdout is the JSON-RPC
// transport in MCP mode. Progress messages go to stderr.

// hostPlatform is the machine this forge runs on, which is what an entry
// that declares no platform builds for.
func hostPlatform() string {
	return runtime.GOOS + "/" + runtime.GOARCH
}

// platformsFor answers what one entry builds: every platform it declares,
// the host when it declares none. Nothing narrows it and nothing widens
// it: the entry declares, the host is the one fact the machine states.
// There is no flag - a distribution is what the entries say it is, and an
// entry that declares no platform is a repo's own tool that stays home.
func platformsFor(spec forge.BuildSpec) []string {
	if len(spec.Platforms) == 0 {
		return []string{hostPlatform()}
	}

	return spec.Platforms
}

func buildAll(artifactName string) (*BuildAllResult, error) {
	// Load forge.yaml configuration
	config, err := loadConfig()
	if err != nil {
		return nil, fmt.Errorf("failed to load forge.yaml: %w", err)
	}

	// How strictly this repo builds is declared once, in forge.yaml.
	frozenBuild := config.FrozenBuild()

	// Read artifact store
	store, err := forge.ReadOrCreateArtifactStore(config.ArtifactStorePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read artifact store: %w", err)
	}

	// Group consecutive same-engine specs, preserving declaration order.
	var groups []engineGroup
	result := &BuildAllResult{}

	// Track cleanup functions for git-cloned context directories.
	// Temp dirs must persist until all engine builds complete because specs
	// are grouped by engine and sent as a batch -- cleanup after all builds.
	var cleanups []func()
	defer func() {
		for _, fn := range cleanups {
			fn()
		}
	}()

	matched := 0
	owned := config.OwnedBuilds()

	for _, spec := range config.Build {
		if artifactName != "" && spec.Name != artifactName {
			continue
		}

		// An entry a test stage needs is that stage's to build. A bare build
		// leaves it alone; naming it builds it.
		if artifactName == "" {
			if owner, ok := owned[spec.Name]; ok {
				fmt.Fprintf(os.Stderr, "⏭  Skipping %s (built by the %s stage that needs it)\n", spec.Name, owner)

				continue
			}
		}

		matched++

		// What this entry builds: what it declares, or the host.
		platforms := platformsFor(spec)

		// Whether anything may be reused is the engine's to declare, and
		// nothing declares it by default: a generator's output depends on
		// the generator, which no record holds, so it runs every time. For
		// an engine that does declare it the record decides, per platform,
		// because a fresh host binary says nothing about the arm64 one.
		needsRebuild, reason := true, "the engine declares no incremental build"

		if engineIsIncremental(spec.Engine, &config) {
			var err error

			needsRebuild, reason, err = shouldRebuild(spec.Name, platforms, store)
			if err != nil {
				// If error checking rebuild status, log warning and rebuild (safe default)
				fmt.Fprintf(os.Stderr, "Warning: failed to check rebuild status for %s: %v (will rebuild)\n", spec.Name, err)
				needsRebuild = true
				reason = "rebuild check failed"
			}
		}

		if !needsRebuild {
			// Skip this artifact - it's up to date
			fmt.Fprintf(os.Stderr, "⏭  Skipping %s (unchanged)\n", spec.Name)
			result.Skipped++
			continue
		}

		// Log reason for rebuild if provided
		if reason != "" {
			fmt.Fprintf(os.Stderr, "🔨 Building %s (%s)\n", spec.Name, reason)
		}

		engine := spec.Engine

		// Resolve build context
		contextDir, cleanup, err := resolveContextDir(spec.Context)
		if err != nil {
			return nil, fmt.Errorf("failed to resolve context for %s: %w", spec.Name, err)
		}
		cleanups = append(cleanups, cleanup)

		// Resolve src relative to context directory.
		// Only join if spec.Src is relative AND context is explicitly set.
		resolvedSrc := spec.Src
		if spec.Context != "" && spec.Context != "." && !filepath.IsAbs(spec.Src) {
			resolvedSrc = filepath.Join(contextDir, spec.Src)
		}

		params := map[string]any{
			"name":      spec.Name,
			"src":       resolvedSrc,
			"dest":      spec.Dest,
			"context":   contextDir,
			"engine":    engine,
			"platforms": platforms,
		}

		// Pass engine-specific configuration if provided
		// Nest under "spec" key so engines can access it via BuildInput.Spec
		if len(spec.Spec) > 0 {
			params["spec"] = spec.Spec
		}

		groups = appendSpecToGroups(groups, engine, params)
	}

	if artifactName != "" && matched == 0 {
		return nil, fmt.Errorf("no artifact found with name: %s", artifactName)
	}

	if len(groups) == 0 {
		// Either all skipped or no artifacts to build
		return result, nil
	}

	// Create forge directories for build operations
	dirs, err := createForgeDirs()
	if err != nil {
		return nil, fmt.Errorf("failed to create forge directories: %w", err)
	}

	// Clean up old tmp directories (keep last 10 runs)
	if err := cleanupOldTmpDirs(10); err != nil {
		// Log warning but don't fail
		fmt.Fprintf(os.Stderr, "Warning: failed to cleanup old tmp directories: %v\n", err)
	}

	// Build each group in declaration order using the appropriate engine
	for _, group := range groups {
		engineURI, specs := group.engine, group.specs
		fmt.Fprintf(os.Stderr, "Building %d artifact(s) with %s...\n", len(specs), engineURI)

		// Check if this is a multi-engine alias
		var artifacts []forge.Artifact
		if strings.HasPrefix(engineURI, "alias://") {
			aliasName := strings.TrimPrefix(engineURI, "alias://")
			engineConfig := getEngineConfig(aliasName, &config)
			if engineConfig == nil {
				result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("engine alias not found: %s", aliasName))
				continue
			}

			if engineConfig.Type == forge.BuilderEngineConfigType && len(engineConfig.Builder) > 1 {
				// Multi-engine builder - use orchestrator
				fmt.Fprintf(os.Stderr, "  Multi-engine builder detected (%d engines)\n", len(engineConfig.Builder))

				orchestrator := orchestrate.NewBuilderOrchestrator(
					callMCPEngine,
					func(uri string) (string, []string, error) {
						return resolveEngine(uri, &config)
					},
				)

				// Prepare directories map
				dirsMap := map[string]any{
					"tmpDir":   dirs.TmpDir,
					"buildDir": dirs.BuildDir,
					"rootDir":  dirs.RootDir,
				}

				// Execute orchestration
				artifacts, err = orchestrator.Orchestrate(engineConfig.Builder, specs, dirsMap)
				if err != nil {
					result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("multi-engine build failed: %v", err))
					continue
				}
			} else {
				// Single-engine alias - resolve to actual engine
				command, args, err := resolveEngine(engineURI, &config)
				if err != nil {
					result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("failed to resolve engine %s: %v", engineURI, err))
					continue
				}

				artifacts, err = buildWithSingleEngine(command, args, specs, dirs, engineConfig, frozenBuild)
				if err != nil {
					result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("build failed for %s: %v", engineURI, err))
					continue
				}
			}
		} else {
			// Direct forge:// URI - single engine
			command, args, err := resolveEngine(engineURI, &config)
			if err != nil {
				result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("failed to resolve engine %s: %v", engineURI, err))
				continue
			}

			artifacts, err = buildWithSingleEngine(command, args, specs, dirs, nil, frozenBuild)
			if err != nil {
				result.BuildErrors = append(result.BuildErrors, fmt.Sprintf("build failed for %s: %v", engineURI, err))
				continue
			}
		}

		// Update artifact store
		for _, artifact := range artifacts {
			forge.AddOrUpdateArtifact(&store, artifact)
			result.Artifacts = append(result.Artifacts, artifact)
			result.TotalBuilt++
		}

		// Written after every group, not once at the end: a later entry may
		// read this repository's own records (an image assembled from the
		// binaries the entries before it built), and it reads them from the
		// file. Held in memory until the end, the store did not exist on a
		// fresh clone when that entry ran, and it failed on its own repo.
		if err := forge.WriteArtifactStore(config.ArtifactStorePath, store); err != nil {
			return nil, fmt.Errorf("failed to write artifact store: %w", err)
		}
	}

	// If there were build errors, return them as an error
	if len(result.BuildErrors) > 0 {
		return result, fmt.Errorf("build completed with errors: %v", result.BuildErrors)
	}

	return result, nil
}

// shouldRebuild answers whether an artifact needs building, for every
// platform the entry builds. The first platform whose record is missing or
// stale decides, because one engine call builds them all.
func shouldRebuild(artifactName string, platforms []string, store forge.ArtifactStore) (bool, string, error) {
	for _, platform := range platforms {
		rebuild, reason, err := platformNeedsRebuild(artifactName, platform, store)
		if err != nil || rebuild {
			return rebuild, reason, err
		}
	}

	return false, "", nil
}

// platformNeedsRebuild is the whole of the freshness rule, and it knows no
// language, no filename and no clock: no record, or a record with no
// dependencies, rebuilds; any recorded path that is missing or whose
// content digest differs rebuilds; an output that carries a digest and is
// missing or differs rebuilds. Nothing else does. What a dependency is was
// decided by the detector or the engine that recorded it, and a generator
// records what it wrote beside what it read, so a hand-edited generated
// file is stale by the same rule as an edited source.
func platformNeedsRebuild(artifactName, platform string, store forge.ArtifactStore) (bool, string, error) {
	artifact, err := forge.GetLatestArtifact(store, artifactName, platform)
	if err != nil {
		artifact, err = forge.GetLatestArtifact(store, artifactName, "")
	}

	if err != nil {
		return true, "no previous build for " + platform, nil
	}

	if len(artifact.Dependencies) == 0 {
		return true, "dependencies not tracked", nil
	}

	for _, dep := range artifact.Dependencies {
		current, err := forge.DigestFile(dep.Path)
		if err != nil {
			if os.IsNotExist(err) || errors.Is(err, os.ErrNotExist) {
				return true, fmt.Sprintf("dependency %s missing", dep.Path), nil
			}

			return true, fmt.Sprintf("cannot read dependency %s: %v", dep.Path, err), nil
		}

		if current != dep.Digest {
			return true, fmt.Sprintf("dependency %s changed", dep.Path), nil
		}
	}

	if artifact.Digest != "" {
		location := strings.TrimPrefix(artifact.Location, "file://")

		current, err := forge.DigestFile(location)
		if err != nil {
			return true, fmt.Sprintf("artifact %s missing for %s", location, platform), nil
		}

		if current != artifact.Digest {
			return true, fmt.Sprintf("artifact %s changed since it was built", location), nil
		}
	}

	return false, "", nil
}

// buildWithSingleEngine handles building with a single engine (either direct forge:// URI or single-engine alias).
func buildWithSingleEngine(
	command string,
	args []string,
	specs []map[string]any,
	dirs *ForgeDirs,
	engineConfig *forge.EngineConfig,
	frozenBuild bool,
) ([]forge.Artifact, error) {
	// Ask the engine what it declares before handing it anything optional.
	readsFrozen := engineReadsFrozen(command, args)

	// Prepare specs with injected directories and config
	specsWithConfig := make([]map[string]any, len(specs))
	for i, spec := range specs {
		// Clone the spec
		clonedSpec := make(map[string]any)
		for k, v := range spec {
			clonedSpec[k] = v
		}

		// Inject directories
		clonedSpec["tmpDir"] = dirs.TmpDir
		clonedSpec["buildDir"] = dirs.BuildDir
		clonedSpec["rootDir"] = dirs.RootDir

		// The repo's frozen setting reaches only an engine that declared it
		// reads one. Sent to every engine it would be silently ignored by
		// most, and an engine that never declared it refuses it by name.
		if readsFrozen {
			clonedSpec["frozen"] = frozenBuild
		}

		// Inject engine-specific config if provided (from alias)
		// For generic engines, promote spec fields to top level for backward compatibility
		if engineConfig != nil && engineConfig.Type == forge.BuilderEngineConfigType && len(engineConfig.Builder) > 0 {
			builderSpec := engineConfig.Builder[0].Spec
			if builderSpec.Command != "" {
				clonedSpec["command"] = builderSpec.Command
			}
			if len(builderSpec.Args) > 0 {
				clonedSpec["args"] = builderSpec.Args
			}
			if len(builderSpec.Env) > 0 {
				clonedSpec["env"] = builderSpec.Env
			}
			if builderSpec.EnvFile != "" {
				clonedSpec["envFile"] = builderSpec.EnvFile
			}
			if builderSpec.Context != "" {
				clonedSpec["context"] = builderSpec.Context
			}
		} else if nestedSpec, ok := spec["spec"].(map[string]interface{}); ok {
			// Keep the spec nested - engines expect it in input.Spec
			// Convert to map[string]any for consistency
			specMap := make(map[string]any)
			for k, v := range nestedSpec {
				specMap[k] = v
			}
			clonedSpec["spec"] = specMap
		}

		specsWithConfig[i] = clonedSpec
	}

	// Call MCP engine (use build for single spec, buildBatch for multiple)
	var mcpResult interface{}
	var err error
	if len(specsWithConfig) == 1 {
		mcpResult, err = callMCPEngine(command, args, "build", specsWithConfig[0])
	} else {
		params := map[string]any{
			"specs": specsWithConfig,
		}
		mcpResult, err = callMCPEngine(command, args, "buildBatch", params)
	}

	if err != nil {
		return nil, err
	}

	// Parse and return artifacts
	artifacts, err := parseArtifacts(mcpResult)
	if err != nil {
		return nil, err
	}

	return artifacts, nil
}

// engineCapabilities asks an engine, over its config-validate tool, what it
// declares. An engine that answers nothing - a hand-written one, a third
// party's - declares nothing, and the caller neither sends it an input it
// did not ask for nor reuses output it never said was reusable. Cached by
// engine: the declaration does not depend on the entry.
var declaredCapabilities = map[string]map[string]any{}

func engineCapabilities(command string, args []string) map[string]any {
	key := command + " " + strings.Join(args, " ")
	if declared, ok := declaredCapabilities[key]; ok {
		return declared
	}

	declaredCapabilities[key] = map[string]any{}

	result, err := callMCPEngine(command, args, "config-validate", map[string]any{"spec": map[string]any{}})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: %s answered no capabilities (%v); it is told nothing and reuses nothing\n", command, err)

		return declaredCapabilities[key]
	}

	data, err := json.Marshal(result)
	if err != nil {
		return declaredCapabilities[key]
	}

	var output struct {
		Capabilities map[string]any `json:"capabilities"`
	}

	if err := json.Unmarshal(data, &output); err != nil {
		return declaredCapabilities[key]
	}

	if output.Capabilities != nil {
		declaredCapabilities[key] = output.Capabilities
	}

	return declaredCapabilities[key]
}

// engineReadsFrozen answers whether the engine declared it reads a frozen
// input.
func engineReadsFrozen(command string, args []string) bool {
	frozen, _ := engineCapabilities(command, args)["frozen"].(bool)

	return frozen
}

// engineIsIncremental answers whether the engine declared that its output
// may be reused while its recorded inputs are unchanged. Nothing is skipped
// for an engine that did not: a generator's output depends on the generator
// and no record holds that, so a generator runs every time.
func engineIsIncremental(engineURI string, spec *forge.Spec) bool {
	command, args, err := resolveEngine(engineURI, spec)
	if err != nil {
		return false
	}

	incremental, _ := engineCapabilities(command, args)["incremental"].(bool)

	return incremental
}

// parseArtifacts converts MCP result to forge.Artifact slice.
func parseArtifacts(result interface{}) ([]forge.Artifact, error) {
	// Result could be:
	// 1. A single artifact object
	// 2. An array of artifacts
	// 3. A BatchResult object (from buildBatch) containing an artifacts array

	// Try to convert to JSON and back to parse it
	data, err := json.Marshal(result)
	if err != nil {
		return nil, err
	}

	// Try parsing as BatchResult first (from buildBatch operations)
	type BatchResult struct {
		Artifacts []forge.Artifact `json:"artifacts"`
	}
	var batchResult BatchResult
	if err := json.Unmarshal(data, &batchResult); err == nil && len(batchResult.Artifacts) > 0 {
		return batchResult.Artifacts, nil
	}

	// Try parsing as single artifact
	var singleArtifact forge.Artifact
	if err := json.Unmarshal(data, &singleArtifact); err == nil && singleArtifact.Name != "" {
		return []forge.Artifact{singleArtifact}, nil
	}

	// Try parsing as array of artifacts
	var multipleArtifacts []forge.Artifact
	if err := json.Unmarshal(data, &multipleArtifacts); err == nil {
		return multipleArtifacts, nil
	}

	return nil, fmt.Errorf("could not parse artifacts from result")
}
