// Code generated by forge-dev. DO NOT EDIT.
// Source: spec.openapi.yaml
// SourceChecksum: sha256:42aaebe88f19fe9102f0be798f12248b9802b5a85b0b7cfd22b14a1e4affeb87

package main

import (
	"fmt"
)

// Spec represents the Spec configuration.
// Configuration for generic-test-runner engine
type Spec struct {
	// Command arguments (optional)
	Args []string `json:"args,omitempty"`
	// Command to execute (required)
	Command string `json:"command"`
	// Context directory for command execution (optional)
	Context string `json:"context,omitempty"`
	// Environment variables (optional)
	Env map[string]string `json:"env,omitempty"`
	// Path to environment file (optional)
	EnvFile string `json:"envFile,omitempty"`
}

// SpecFromMap creates a Spec from a map[string]interface{}.
func SpecFromMap(m map[string]interface{}) (*Spec, error) {
	if m == nil {
		return &Spec{}, nil
	}

	s := &Spec{}

	// A key the schema does not name is refused, by name, with the keys
	// it could have been. A spec that silently dropped it read as
	// configuration that took effect: forge's own ldflags on go-build was
	// exactly that for weeks.
	for key := range m {
		switch key {
		case "args":
		case "command":
		case "context":
		case "env":
		case "envFile":
		default:
			return nil, fmt.Errorf("field %s: not a key of Spec; the keys are args, command, context, env, envFile", key)
		}
	}
	// Parse args
	if v, ok := m["args"]; ok && v != nil {
		if arr, ok := v.([]interface{}); ok {
			s.Args = make([]string, 0, len(arr))
			for i, item := range arr {
				if str, ok := item.(string); ok {
					s.Args = append(s.Args, str)
				} else {
					return nil, fmt.Errorf("field args[%d]: expected string, got %T", i, item)
				}
			}
		} else if arr, ok := v.([]string); ok {
			s.Args = arr
		} else {
			return nil, fmt.Errorf("field args: expected []string, got %T", v)
		}
	}
	// Parse command
	if v, ok := m["command"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Command = val
		} else {
			return nil, fmt.Errorf("field command: expected string, got %T", v)
		}
	}
	// Parse context
	if v, ok := m["context"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.Context = val
		} else {
			return nil, fmt.Errorf("field context: expected string, got %T", v)
		}
	}
	// Parse env
	if v, ok := m["env"]; ok && v != nil {
		if mapVal, ok := v.(map[string]interface{}); ok {
			s.Env = make(map[string]string, len(mapVal))
			for key, val := range mapVal {
				if str, ok := val.(string); ok {
					s.Env[key] = str
				} else {
					return nil, fmt.Errorf("field env[%s]: expected string, got %T", key, val)
				}
			}
		} else if mapVal, ok := v.(map[string]string); ok {
			s.Env = mapVal
		} else {
			return nil, fmt.Errorf("field env: expected map[string]string, got %T", v)
		}
	}
	// Parse envFile
	if v, ok := m["envFile"]; ok && v != nil {
		if val, ok := v.(string); ok {
			s.EnvFile = val
		} else {
			return nil, fmt.Errorf("field envFile: expected string, got %T", v)
		}
	}
	return s, nil
}

// ToMap converts a Spec to a map[string]interface{}.
func (s *Spec) ToMap() map[string]interface{} {
	if s == nil {
		return nil
	}

	m := make(map[string]interface{})
	if len(s.Args) > 0 {
		m["args"] = s.Args
	}
	if s.Command != "" {
		m["command"] = s.Command
	}
	if s.Context != "" {
		m["context"] = s.Context
	}
	if len(s.Env) > 0 {
		m["env"] = s.Env
	}
	if s.EnvFile != "" {
		m["envFile"] = s.EnvFile
	}
	return m
}

// FromMap creates a Spec from a map[string]interface{}.
// This is the main entry point for parsing the spec field from forge.yaml.
func FromMap(m map[string]interface{}) (*Spec, error) {
	return SpecFromMap(m)
}
